// Code generated by acp-schema from the method table; DO NOT EDIT.

package acp

import schema "github.com/ironpark/go-acp/schema/v1"

// ProtocolVersion is the ACP protocol version implemented by this package.
const ProtocolVersion = schema.CurrentProtocolVersion

// Every request, response and notification payload, re-exported so that a
// caller implementing [Agent] or [Client] needs one import. Other generated
// types live in the schema package.

type (
	WriteTextFileRequest            = schema.WriteTextFileRequest
	ReadTextFileRequest             = schema.ReadTextFileRequest
	RequestPermissionRequest        = schema.RequestPermissionRequest
	CreateTerminalRequest           = schema.CreateTerminalRequest
	TerminalOutputRequest           = schema.TerminalOutputRequest
	ReleaseTerminalRequest          = schema.ReleaseTerminalRequest
	WaitForTerminalExitRequest      = schema.WaitForTerminalExitRequest
	KillTerminalRequest             = schema.KillTerminalRequest
	CreateElicitationRequest        = schema.CreateElicitationRequest
	ConnectMCPRequest               = schema.ConnectMCPRequest
	MessageMCPRequest               = schema.MessageMCPRequest
	DisconnectMCPRequest            = schema.DisconnectMCPRequest
	ExtRequest                      = schema.ExtRequest
	InitializeResponse              = schema.InitializeResponse
	AuthenticateResponse            = schema.AuthenticateResponse
	ListProvidersResponse           = schema.ListProvidersResponse
	SetProviderResponse             = schema.SetProviderResponse
	DisableProviderResponse         = schema.DisableProviderResponse
	LogoutResponse                  = schema.LogoutResponse
	NewSessionResponse              = schema.NewSessionResponse
	LoadSessionResponse             = schema.LoadSessionResponse
	ListSessionsResponse            = schema.ListSessionsResponse
	DeleteSessionResponse           = schema.DeleteSessionResponse
	ForkSessionResponse             = schema.ForkSessionResponse
	ResumeSessionResponse           = schema.ResumeSessionResponse
	CloseSessionResponse            = schema.CloseSessionResponse
	SetSessionModeResponse          = schema.SetSessionModeResponse
	SetSessionConfigOptionResponse  = schema.SetSessionConfigOptionResponse
	PromptResponse                  = schema.PromptResponse
	StartNesResponse                = schema.StartNesResponse
	SuggestNesResponse              = schema.SuggestNesResponse
	CloseNesResponse                = schema.CloseNesResponse
	ExtResponse                     = schema.ExtResponse
	MessageMCPResponse              = schema.MessageMCPResponse
	SessionNotification             = schema.SessionNotification
	CompleteElicitationNotification = schema.CompleteElicitationNotification
	MessageMCPNotification          = schema.MessageMCPNotification
	ExtNotification                 = schema.ExtNotification
	InitializeRequest               = schema.InitializeRequest
	AuthenticateRequest             = schema.AuthenticateRequest
	ListProvidersRequest            = schema.ListProvidersRequest
	SetProviderRequest              = schema.SetProviderRequest
	DisableProviderRequest          = schema.DisableProviderRequest
	LogoutRequest                   = schema.LogoutRequest
	NewSessionRequest               = schema.NewSessionRequest
	LoadSessionRequest              = schema.LoadSessionRequest
	ListSessionsRequest             = schema.ListSessionsRequest
	DeleteSessionRequest            = schema.DeleteSessionRequest
	ForkSessionRequest              = schema.ForkSessionRequest
	ResumeSessionRequest            = schema.ResumeSessionRequest
	CloseSessionRequest             = schema.CloseSessionRequest
	SetSessionModeRequest           = schema.SetSessionModeRequest
	SetSessionConfigOptionRequest   = schema.SetSessionConfigOptionRequest
	PromptRequest                   = schema.PromptRequest
	StartNesRequest                 = schema.StartNesRequest
	SuggestNesRequest               = schema.SuggestNesRequest
	CloseNesRequest                 = schema.CloseNesRequest
	WriteTextFileResponse           = schema.WriteTextFileResponse
	ReadTextFileResponse            = schema.ReadTextFileResponse
	RequestPermissionResponse       = schema.RequestPermissionResponse
	CreateTerminalResponse          = schema.CreateTerminalResponse
	TerminalOutputResponse          = schema.TerminalOutputResponse
	ReleaseTerminalResponse         = schema.ReleaseTerminalResponse
	WaitForTerminalExitResponse     = schema.WaitForTerminalExitResponse
	KillTerminalResponse            = schema.KillTerminalResponse
	CreateElicitationResponse       = schema.CreateElicitationResponse
	ConnectMCPResponse              = schema.ConnectMCPResponse
	DisconnectMCPResponse           = schema.DisconnectMCPResponse
	CancelNotification              = schema.CancelNotification
	DidOpenDocumentNotification     = schema.DidOpenDocumentNotification
	DidChangeDocumentNotification   = schema.DidChangeDocumentNotification
	DidCloseDocumentNotification    = schema.DidCloseDocumentNotification
	DidSaveDocumentNotification     = schema.DidSaveDocumentNotification
	DidFocusDocumentNotification    = schema.DidFocusDocumentNotification
	AcceptNesNotification           = schema.AcceptNesNotification
	RejectNesNotification           = schema.RejectNesNotification
	CancelRequestNotification       = schema.CancelRequestNotification
)

// Identifiers and values shared across those payloads.

type (
	SessionID           = schema.SessionID
	SessionInfo         = schema.SessionInfo
	SessionModeID       = schema.SessionModeID
	SessionConfigOption = schema.SessionConfigOption
	SessionUpdate       = schema.SessionUpdate
	MessageID           = schema.MessageID
	TerminalID          = schema.TerminalID
	ToolCallID          = schema.ToolCallID
	ToolCallContent     = schema.ToolCallContent
	ToolCallLocation    = schema.ToolCallLocation
	ToolCallStatus      = schema.ToolCallStatus
	ToolKind            = schema.ToolKind
	ContentBlock        = schema.ContentBlock
	PlanEntry           = schema.PlanEntry
	AvailableCommand    = schema.AvailableCommand
	Cost                = schema.Cost
	StopReason          = schema.StopReason
)
