// Code generated by acp-schema from the method table; DO NOT EDIT.

package acp2

import schema "github.com/ironpark/acp-go/schema/v2"

// ProtocolVersion is the ACP protocol version implemented by this package.
const ProtocolVersion = schema.CurrentProtocolVersion

// Every request, response and notification payload, re-exported so that a
// caller implementing [Agent] or [Client] needs one import. Other generated
// types live in the schema package.

type (
	RequestPermissionRequest        = schema.RequestPermissionRequest
	CreateElicitationRequest        = schema.CreateElicitationRequest
	ConnectMCPRequest               = schema.ConnectMCPRequest
	MessageMCPRequest               = schema.MessageMCPRequest
	DisconnectMCPRequest            = schema.DisconnectMCPRequest
	ExtRequest                      = schema.ExtRequest
	InitializeResponse              = schema.InitializeResponse
	LoginAuthResponse               = schema.LoginAuthResponse
	ListProvidersResponse           = schema.ListProvidersResponse
	SetProviderResponse             = schema.SetProviderResponse
	DisableProviderResponse         = schema.DisableProviderResponse
	LogoutAuthResponse              = schema.LogoutAuthResponse
	NewSessionResponse              = schema.NewSessionResponse
	ListSessionsResponse            = schema.ListSessionsResponse
	DeleteSessionResponse           = schema.DeleteSessionResponse
	ForkSessionResponse             = schema.ForkSessionResponse
	ResumeSessionResponse           = schema.ResumeSessionResponse
	CloseSessionResponse            = schema.CloseSessionResponse
	SetSessionConfigOptionResponse  = schema.SetSessionConfigOptionResponse
	PromptResponse                  = schema.PromptResponse
	StartNesResponse                = schema.StartNesResponse
	SuggestNesResponse              = schema.SuggestNesResponse
	CloseNesResponse                = schema.CloseNesResponse
	ExtResponse                     = schema.ExtResponse
	MessageMCPResponse              = schema.MessageMCPResponse
	UpdateSessionNotification       = schema.UpdateSessionNotification
	CompleteElicitationNotification = schema.CompleteElicitationNotification
	MessageMCPNotification          = schema.MessageMCPNotification
	ExtNotification                 = schema.ExtNotification
	InitializeRequest               = schema.InitializeRequest
	LoginAuthRequest                = schema.LoginAuthRequest
	ListProvidersRequest            = schema.ListProvidersRequest
	SetProviderRequest              = schema.SetProviderRequest
	DisableProviderRequest          = schema.DisableProviderRequest
	LogoutAuthRequest               = schema.LogoutAuthRequest
	NewSessionRequest               = schema.NewSessionRequest
	ListSessionsRequest             = schema.ListSessionsRequest
	DeleteSessionRequest            = schema.DeleteSessionRequest
	ForkSessionRequest              = schema.ForkSessionRequest
	ResumeSessionRequest            = schema.ResumeSessionRequest
	CloseSessionRequest             = schema.CloseSessionRequest
	SetSessionConfigOptionRequest   = schema.SetSessionConfigOptionRequest
	PromptRequest                   = schema.PromptRequest
	StartNesRequest                 = schema.StartNesRequest
	SuggestNesRequest               = schema.SuggestNesRequest
	CloseNesRequest                 = schema.CloseNesRequest
	RequestPermissionResponse       = schema.RequestPermissionResponse
	CreateElicitationResponse       = schema.CreateElicitationResponse
	ConnectMCPResponse              = schema.ConnectMCPResponse
	DisconnectMCPResponse           = schema.DisconnectMCPResponse
	CancelSessionNotification       = schema.CancelSessionNotification
	DidOpenDocumentNotification     = schema.DidOpenDocumentNotification
	DidChangeDocumentNotification   = schema.DidChangeDocumentNotification
	DidCloseDocumentNotification    = schema.DidCloseDocumentNotification
	DidSaveDocumentNotification     = schema.DidSaveDocumentNotification
	DidFocusDocumentNotification    = schema.DidFocusDocumentNotification
	AcceptNesNotification           = schema.AcceptNesNotification
	RejectNesNotification           = schema.RejectNesNotification
	CancelRequestNotification       = schema.CancelRequestNotification
)

// Identifiers and values shared across those payloads, with the constants
// and variants that come with them.

type (
	SessionID                            = schema.SessionID
	SessionInfo                          = schema.SessionInfo
	SessionConfigOption                  = schema.SessionConfigOption
	SessionConfigOptionVariant           = schema.SessionConfigOptionVariant
	SessionConfigOptionVariants          = schema.SessionConfigOptionVariants
	SessionConfigOptionSelect            = schema.SessionConfigOptionSelect
	SessionConfigOptionBoolean           = schema.SessionConfigOptionBoolean
	SessionConfigOptionCustom            = schema.SessionConfigOptionCustom
	SessionUpdate                        = schema.SessionUpdate
	SessionUpdateVariant                 = schema.SessionUpdateVariant
	SessionUpdateVariants                = schema.SessionUpdateVariants
	SessionUpdateUserMessageChunk        = schema.SessionUpdateUserMessageChunk
	SessionUpdateUserMessage             = schema.SessionUpdateUserMessage
	SessionUpdateAgentMessageChunk       = schema.SessionUpdateAgentMessageChunk
	SessionUpdateAgentMessage            = schema.SessionUpdateAgentMessage
	SessionUpdateAgentThoughtChunk       = schema.SessionUpdateAgentThoughtChunk
	SessionUpdateAgentThought            = schema.SessionUpdateAgentThought
	SessionUpdateStateUpdate             = schema.SessionUpdateStateUpdate
	SessionUpdateToolCallContentChunk    = schema.SessionUpdateToolCallContentChunk
	SessionUpdateToolCallUpdate          = schema.SessionUpdateToolCallUpdate
	SessionUpdateTerminalUpdate          = schema.SessionUpdateTerminalUpdate
	SessionUpdateTerminalOutputChunk     = schema.SessionUpdateTerminalOutputChunk
	SessionUpdatePlanUpdate              = schema.SessionUpdatePlanUpdate
	SessionUpdatePlanRemoved             = schema.SessionUpdatePlanRemoved
	SessionUpdateAvailableCommandsUpdate = schema.SessionUpdateAvailableCommandsUpdate
	SessionUpdateConfigOptionUpdate      = schema.SessionUpdateConfigOptionUpdate
	SessionUpdateSessionInfoUpdate       = schema.SessionUpdateSessionInfoUpdate
	SessionUpdateUsageUpdate             = schema.SessionUpdateUsageUpdate
	SessionUpdateNotice                  = schema.SessionUpdateNotice
	SessionUpdateCompactionUpdate        = schema.SessionUpdateCompactionUpdate
	SessionUpdateCompactionSummaryChunk  = schema.SessionUpdateCompactionSummaryChunk
	SessionUpdateCustom                  = schema.SessionUpdateCustom
	MessageID                            = schema.MessageID
	ToolCallID                           = schema.ToolCallID
	ContentBlock                         = schema.ContentBlock
	ContentBlockVariant                  = schema.ContentBlockVariant
	ContentBlockVariants                 = schema.ContentBlockVariants
	ContentBlockText                     = schema.ContentBlockText
	ContentBlockImage                    = schema.ContentBlockImage
	ContentBlockAudio                    = schema.ContentBlockAudio
	ContentBlockResourceLink             = schema.ContentBlockResourceLink
	ContentBlockResource                 = schema.ContentBlockResource
	ContentBlockCustom                   = schema.ContentBlockCustom
	AbsolutePath                         = schema.AbsolutePath
	MCPConnectionID                      = schema.MCPConnectionID
	MCPServerACPID                       = schema.MCPServerACPID
	StopReason                           = schema.StopReason
	ToolCallContent                      = schema.ToolCallContent
	ToolCallContentVariant               = schema.ToolCallContentVariant
	ToolCallContentVariants              = schema.ToolCallContentVariants
	ToolCallContentContent               = schema.ToolCallContentContent
	ToolCallContentDiff                  = schema.ToolCallContentDiff
	ToolCallContentTerminal              = schema.ToolCallContentTerminal
	ToolCallContentCustom                = schema.ToolCallContentCustom
	ToolCallLocation                     = schema.ToolCallLocation
	ToolCallStatus                       = schema.ToolCallStatus
	ToolKind                             = schema.ToolKind
	AvailableCommand                     = schema.AvailableCommand
	Cost                                 = schema.Cost
	Implementation                       = schema.Implementation
	PermissionOption                     = schema.PermissionOption
	PermissionOptionKind                 = schema.PermissionOptionKind
	ToolCallUpdate                       = schema.ToolCallUpdate
	RequestPermissionOutcome             = schema.RequestPermissionOutcome
	RequestPermissionOutcomeVariant      = schema.RequestPermissionOutcomeVariant
	RequestPermissionOutcomeVariants     = schema.RequestPermissionOutcomeVariants
	RequestPermissionOutcomeCancelled    = schema.RequestPermissionOutcomeCancelled
	RequestPermissionOutcomeSelected     = schema.RequestPermissionOutcomeSelected
	RequestPermissionOutcomeCustom       = schema.RequestPermissionOutcomeCustom
	PlanEntryStatus                      = schema.PlanEntryStatus
	PlanEntryPriority                    = schema.PlanEntryPriority
	ReplayFrom                           = schema.ReplayFrom
	ReplayFromVariant                    = schema.ReplayFromVariant
	ReplayFromVariants                   = schema.ReplayFromVariants
	ReplayFromStart                      = schema.ReplayFromStart
	ReplayFromCustom                     = schema.ReplayFromCustom
	MCPServer                            = schema.MCPServer
	MCPServerVariant                     = schema.MCPServerVariant
	MCPServerVariants                    = schema.MCPServerVariants
	MCPServerHTTP                        = schema.MCPServerHTTP
	MCPServerACP                         = schema.MCPServerACP
	MCPServerStdio                       = schema.MCPServerStdio
	MCPServerCustom                      = schema.MCPServerCustom
	Meta                                 = schema.Meta
)

const (
	StopReasonEndTurn                = schema.StopReasonEndTurn
	StopReasonMaxTokens              = schema.StopReasonMaxTokens
	StopReasonMaxTurnRequests        = schema.StopReasonMaxTurnRequests
	StopReasonRefusal                = schema.StopReasonRefusal
	StopReasonCancelled              = schema.StopReasonCancelled
	ToolCallStatusPending            = schema.ToolCallStatusPending
	ToolCallStatusInProgress         = schema.ToolCallStatusInProgress
	ToolCallStatusCompleted          = schema.ToolCallStatusCompleted
	ToolCallStatusFailed             = schema.ToolCallStatusFailed
	ToolCallStatusCancelled          = schema.ToolCallStatusCancelled
	ToolKindRead                     = schema.ToolKindRead
	ToolKindEdit                     = schema.ToolKindEdit
	ToolKindDelete                   = schema.ToolKindDelete
	ToolKindMove                     = schema.ToolKindMove
	ToolKindSearch                   = schema.ToolKindSearch
	ToolKindExecute                  = schema.ToolKindExecute
	ToolKindThink                    = schema.ToolKindThink
	ToolKindFetch                    = schema.ToolKindFetch
	ToolKindSwitchMode               = schema.ToolKindSwitchMode
	ToolKindOther                    = schema.ToolKindOther
	PermissionOptionKindAllowOnce    = schema.PermissionOptionKindAllowOnce
	PermissionOptionKindAllowAlways  = schema.PermissionOptionKindAllowAlways
	PermissionOptionKindRejectOnce   = schema.PermissionOptionKindRejectOnce
	PermissionOptionKindRejectAlways = schema.PermissionOptionKindRejectAlways
	PlanEntryStatusPending           = schema.PlanEntryStatusPending
	PlanEntryStatusInProgress        = schema.PlanEntryStatusInProgress
	PlanEntryStatusCompleted         = schema.PlanEntryStatusCompleted
	PlanEntryStatusCancelled         = schema.PlanEntryStatusCancelled
	PlanEntryPriorityHigh            = schema.PlanEntryPriorityHigh
	PlanEntryPriorityMedium          = schema.PlanEntryPriorityMedium
	PlanEntryPriorityLow             = schema.PlanEntryPriorityLow
)

// NewSessionConfigOption wraps a variant.
func NewSessionConfigOption[T SessionConfigOptionVariants](v T) SessionConfigOption {
	return schema.NewSessionConfigOption(v)
}

// NewSessionUpdate wraps a variant.
func NewSessionUpdate[T SessionUpdateVariants](v T) SessionUpdate { return schema.NewSessionUpdate(v) }

// NewContentBlock wraps a variant.
func NewContentBlock[T ContentBlockVariants](v T) ContentBlock { return schema.NewContentBlock(v) }

// NewToolCallContent wraps a variant.
func NewToolCallContent[T ToolCallContentVariants](v T) ToolCallContent {
	return schema.NewToolCallContent(v)
}

// NewRequestPermissionOutcome wraps a variant.
func NewRequestPermissionOutcome[T RequestPermissionOutcomeVariants](v T) RequestPermissionOutcome {
	return schema.NewRequestPermissionOutcome(v)
}

// NewReplayFrom wraps a variant.
func NewReplayFrom[T ReplayFromVariants](v T) ReplayFrom { return schema.NewReplayFrom(v) }

// NewMCPServer wraps a variant.
func NewMCPServer[T MCPServerVariants](v T) MCPServer { return schema.NewMCPServer(v) }
