// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.

package schema

import (
	"slices"
)

// A unique identifier for a conversation session between a client and agent.
//
// Sessions maintain their own context, conversation history, and state,
// allowing multiple independent interactions with the same agent.
//
// See protocol docs: [Session ID](https://agentclientprotocol.com/protocol/v2/draft/session-setup#session-id)
type SessionID string

// Unique identifier for a tool call within a session.
type ToolCallID string

// Categories of tools that can be invoked.
//
// Tool kinds help clients choose appropriate icons and optimize how they
// display tool execution progress.
//
// See protocol docs: [Creating](https://agentclientprotocol.com/protocol/v2/draft/tool-calls#creating)
// ToolKind also accepts values outside the listed constants; use Known to check.
type ToolKind string

const (
	ToolKindRead       ToolKind = "read"
	ToolKindEdit       ToolKind = "edit"
	ToolKindDelete     ToolKind = "delete"
	ToolKindMove       ToolKind = "move"
	ToolKindSearch     ToolKind = "search"
	ToolKindExecute    ToolKind = "execute"
	ToolKindThink      ToolKind = "think"
	ToolKindFetch      ToolKind = "fetch"
	ToolKindSwitchMode ToolKind = "switch_mode"
	ToolKindOther      ToolKind = "other"
)

// ToolKindValues lists the constants defined by the protocol.
var ToolKindValues = []ToolKind{ToolKindRead, ToolKindEdit, ToolKindDelete, ToolKindMove, ToolKindSearch, ToolKindExecute, ToolKindThink, ToolKindFetch, ToolKindSwitchMode, ToolKindOther}

// Known reports whether v is one of the protocol-defined constants.
func (v ToolKind) Known() bool { return slices.Contains(ToolKindValues, v) }

// Execution status of a tool call.
//
// Tool calls progress through different statuses during their lifecycle.
//
// See protocol docs: [Status](https://agentclientprotocol.com/protocol/v2/draft/tool-calls#status)
// ToolCallStatus also accepts values outside the listed constants; use Known to check.
type ToolCallStatus string

const (
	ToolCallStatusPending    ToolCallStatus = "pending"
	ToolCallStatusInProgress ToolCallStatus = "in_progress"
	ToolCallStatusCompleted  ToolCallStatus = "completed"
	ToolCallStatusFailed     ToolCallStatus = "failed"
	ToolCallStatusCancelled  ToolCallStatus = "cancelled"
)

// ToolCallStatusValues lists the constants defined by the protocol.
var ToolCallStatusValues = []ToolCallStatus{ToolCallStatusPending, ToolCallStatusInProgress, ToolCallStatusCompleted, ToolCallStatusFailed, ToolCallStatusCancelled}

// Known reports whether v is one of the protocol-defined constants.
func (v ToolCallStatus) Known() bool { return slices.Contains(ToolCallStatusValues, v) }

// The sender or recipient of messages and data in a conversation.
// Role also accepts values outside the listed constants; use Known to check.
type Role string

const (
	RoleAssistant Role = "assistant"
	RoleUser      Role = "user"
)

// RoleValues lists the constants defined by the protocol.
var RoleValues = []Role{RoleAssistant, RoleUser}

// Known reports whether v is one of the protocol-defined constants.
func (v Role) Known() bool { return slices.Contains(RoleValues, v) }

// An Internet media type identifying the format of protocol content.
type MediaType string

// Theme an icon is designed for.
// IconTheme also accepts values outside the listed constants; use Known to check.
type IconTheme string

const (
	IconThemeLight IconTheme = "light"
	IconThemeDark  IconTheme = "dark"
)

// IconThemeValues lists the constants defined by the protocol.
var IconThemeValues = []IconTheme{IconThemeLight, IconThemeDark}

// Known reports whether v is one of the protocol-defined constants.
func (v IconTheme) Known() bool { return slices.Contains(IconThemeValues, v) }

// Kind of file content represented by a diff change.
// DiffFileType also accepts values outside the listed constants; use Known to check.
type DiffFileType string

const (
	DiffFileTypeText      DiffFileType = "text"
	DiffFileTypeBinary    DiffFileType = "binary"
	DiffFileTypeDirectory DiffFileType = "directory"
	DiffFileTypeSymlink   DiffFileType = "symlink"
)

// DiffFileTypeValues lists the constants defined by the protocol.
var DiffFileTypeValues = []DiffFileType{DiffFileTypeText, DiffFileTypeBinary, DiffFileTypeDirectory, DiffFileTypeSymlink}

// Known reports whether v is one of the protocol-defined constants.
func (v DiffFileType) Known() bool { return slices.Contains(DiffFileTypeValues, v) }

// An absolute filesystem path used by the protocol.
type AbsolutePath string

// Text patch format used by [`DiffPatch`].
// DiffPatchFormat also accepts values outside the listed constants; use Known to check.
type DiffPatchFormat string

const (
	DiffPatchFormatGitPatch DiffPatchFormat = "git_patch"
)

// DiffPatchFormatValues lists the constants defined by the protocol.
var DiffPatchFormatValues = []DiffPatchFormat{DiffPatchFormatGitPatch}

// Known reports whether v is one of the protocol-defined constants.
func (v DiffPatchFormat) Known() bool { return slices.Contains(DiffPatchFormatValues, v) }

// Unique identifier for an agent-owned terminal within a session.
type TerminalID string

// Unique identifier for a permission option.
type PermissionOptionID string

// The type of permission option being presented to the user.
//
// Helps clients choose appropriate icons and UI treatment.
// PermissionOptionKind also accepts values outside the listed constants; use Known to check.
type PermissionOptionKind string

const (
	PermissionOptionKindAllowOnce    PermissionOptionKind = "allow_once"
	PermissionOptionKindAllowAlways  PermissionOptionKind = "allow_always"
	PermissionOptionKindRejectOnce   PermissionOptionKind = "reject_once"
	PermissionOptionKindRejectAlways PermissionOptionKind = "reject_always"
)

// PermissionOptionKindValues lists the constants defined by the protocol.
var PermissionOptionKindValues = []PermissionOptionKind{PermissionOptionKindAllowOnce, PermissionOptionKindAllowAlways, PermissionOptionKindRejectOnce, PermissionOptionKindRejectAlways}

// Known reports whether v is one of the protocol-defined constants.
func (v PermissionOptionKind) Known() bool { return slices.Contains(PermissionOptionKindValues, v) }

// Object schema type.
type ElicitationSchemaType string

const (
	ElicitationSchemaTypeObject ElicitationSchemaType = "object"
)

// String format types for string properties in elicitation schemas.
// StringFormat also accepts values outside the listed constants; use Known to check.
type StringFormat string

const (
	StringFormatEmail    StringFormat = "email"
	StringFormatURI      StringFormat = "uri"
	StringFormatDate     StringFormat = "date"
	StringFormatDateTime StringFormat = "date-time"
)

// StringFormatValues lists the constants defined by the protocol.
var StringFormatValues = []StringFormat{StringFormatEmail, StringFormatURI, StringFormatDate, StringFormatDateTime}

// Known reports whether v is one of the protocol-defined constants.
func (v StringFormat) Known() bool { return slices.Contains(StringFormatValues, v) }

// Unique identifier for an elicitation.
type ElicitationID string

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Unique identifier for an MCP server using the ACP transport.
//
// The value is opaque and generated by the ACP component providing the MCP server. It is
// used by `mcp/connect` to route connection requests back to the component that declared the
// server.
//
// @experimental
type MCPServerACPID string

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// A unique identifier for an active MCP-over-ACP connection.
//
// @experimental
type MCPConnectionID string

// Protocol version identifier.
//
// This version is only bumped for breaking changes.
// Non-breaking changes should be introduced via capabilities.
type ProtocolVersion uint16

// How the agent wants document changes delivered.
type TextDocumentSyncKind string

const (
	TextDocumentSyncKindFull        TextDocumentSyncKind = "full"
	TextDocumentSyncKindIncremental TextDocumentSyncKind = "incremental"
)

// The encoding used for character offsets in positions.
//
// Follows the same conventions as LSP 3.17. The default is UTF-16.
type PositionEncodingKind string

const (
	PositionEncodingKindUtf16 PositionEncodingKind = "utf-16"
	PositionEncodingKindUtf32 PositionEncodingKind = "utf-32"
	PositionEncodingKindUtf8  PositionEncodingKind = "utf-8"
)

// Typed identifier used for auth method values on the wire.
type AuthMethodID string

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Unique identifier for a configurable LLM provider.
//
// @experimental
type ProviderID string

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Well-known API protocol identifiers for LLM providers.
//
// Agents and clients MUST handle unknown protocol identifiers gracefully.
//
// Protocol names beginning with `_` are free for custom use, like other ACP extension methods.
// Protocol names that do not begin with `_` are reserved for the ACP spec.
//
// @experimental
// LlmProtocol also accepts values outside the listed constants; use Known to check.
type LlmProtocol string

const (
	LlmProtocolAnthropic LlmProtocol = "anthropic"
	LlmProtocolOpenai    LlmProtocol = "openai"
	LlmProtocolAzure     LlmProtocol = "azure"
	LlmProtocolVertex    LlmProtocol = "vertex"
	LlmProtocolBedrock   LlmProtocol = "bedrock"
)

// LlmProtocolValues lists the constants defined by the protocol.
var LlmProtocolValues = []LlmProtocol{LlmProtocolAnthropic, LlmProtocolOpenai, LlmProtocolAzure, LlmProtocolVertex, LlmProtocolBedrock}

// Known reports whether v is one of the protocol-defined constants.
func (v LlmProtocol) Known() bool { return slices.Contains(LlmProtocolValues, v) }

// Unique identifier for a session configuration option.
type SessionConfigID string

// Semantic category for a session configuration option.
//
// This is intended to help Clients distinguish broadly common selectors (e.g. model selector vs
// session mode selector vs thought/reasoning level) for UX purposes (keyboard shortcuts, icons,
// placement). It MUST NOT be required for correctness. Clients MUST handle missing or unknown
// categories gracefully.
//
// Category names beginning with `_` are free for custom use, like other ACP extension methods.
// Category names that do not begin with `_` are reserved for the ACP spec.
// SessionConfigOptionCategory also accepts values outside the listed constants; use Known to check.
type SessionConfigOptionCategory string

const (
	SessionConfigOptionCategoryMode         SessionConfigOptionCategory = "mode"
	SessionConfigOptionCategoryModel        SessionConfigOptionCategory = "model"
	SessionConfigOptionCategoryModelConfig  SessionConfigOptionCategory = "model_config"
	SessionConfigOptionCategoryThoughtLevel SessionConfigOptionCategory = "thought_level"
)

// SessionConfigOptionCategoryValues lists the constants defined by the protocol.
var SessionConfigOptionCategoryValues = []SessionConfigOptionCategory{SessionConfigOptionCategoryMode, SessionConfigOptionCategoryModel, SessionConfigOptionCategoryModelConfig, SessionConfigOptionCategoryThoughtLevel}

// Known reports whether v is one of the protocol-defined constants.
func (v SessionConfigOptionCategory) Known() bool {
	return slices.Contains(SessionConfigOptionCategoryValues, v)
}

// Unique identifier for a session configuration option value.
type SessionConfigValueID string

// Unique identifier for a session configuration option value group.
type SessionConfigGroupID string

// An opaque cursor used to paginate `session/list` results.
type SessionListCursor string

// Unique identifier for a message within a session.
type MessageID string

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Unique identifier for an NES suggestion.
//
// @experimental
type NesSuggestionID string

// Predefined error codes for common JSON-RPC and ACP-specific errors.
//
// These codes follow the JSON-RPC 2.0 specification for standard errors
// and use the reserved range (-32000 to -32099) for protocol-specific errors.
// ErrorCode also accepts values outside the listed constants; use Known to check.
type ErrorCode int64

const (
	ErrorCodeParseError             ErrorCode = -32700
	ErrorCodeInvalidRequest         ErrorCode = -32600
	ErrorCodeMethodNotFound         ErrorCode = -32601
	ErrorCodeInvalidParams          ErrorCode = -32602
	ErrorCodeInternalError          ErrorCode = -32603
	ErrorCodeRequestCancelled       ErrorCode = -32800
	ErrorCodeAuthenticationRequired ErrorCode = -32000
	ErrorCodeResourceNotFound       ErrorCode = -32002
)

// ErrorCodeValues lists the constants defined by the protocol.
var ErrorCodeValues = []ErrorCode{ErrorCodeParseError, ErrorCodeInvalidRequest, ErrorCodeMethodNotFound, ErrorCodeInvalidParams, ErrorCodeInternalError, ErrorCodeRequestCancelled, ErrorCodeAuthenticationRequired, ErrorCodeResourceNotFound}

// Known reports whether v is one of the protocol-defined constants.
func (v ErrorCode) Known() bool { return slices.Contains(ErrorCodeValues, v) }

// Reasons why an agent stops active session work.
//
// See protocol docs: [Stop Reasons](https://agentclientprotocol.com/protocol/v2/draft/prompt-lifecycle#stop-reasons)
// StopReason also accepts values outside the listed constants; use Known to check.
type StopReason string

const (
	StopReasonEndTurn         StopReason = "end_turn"
	StopReasonMaxTokens       StopReason = "max_tokens"
	StopReasonMaxTurnRequests StopReason = "max_turn_requests"
	StopReasonRefusal         StopReason = "refusal"
	StopReasonCancelled       StopReason = "cancelled"
)

// StopReasonValues lists the constants defined by the protocol.
var StopReasonValues = []StopReason{StopReasonEndTurn, StopReasonMaxTokens, StopReasonMaxTurnRequests, StopReasonRefusal, StopReasonCancelled}

// Known reports whether v is one of the protocol-defined constants.
func (v StopReason) Known() bool { return slices.Contains(StopReasonValues, v) }

// Unique identifier for a plan within a session.
type PlanID string

// Priority levels for plan entries.
//
// Used to indicate the relative importance or urgency of different
// tasks in the execution plan.
// See protocol docs: [Plan Entries](https://agentclientprotocol.com/protocol/v2/draft/agent-plan#plan-entries)
// PlanEntryPriority also accepts values outside the listed constants; use Known to check.
type PlanEntryPriority string

const (
	PlanEntryPriorityHigh   PlanEntryPriority = "high"
	PlanEntryPriorityMedium PlanEntryPriority = "medium"
	PlanEntryPriorityLow    PlanEntryPriority = "low"
)

// PlanEntryPriorityValues lists the constants defined by the protocol.
var PlanEntryPriorityValues = []PlanEntryPriority{PlanEntryPriorityHigh, PlanEntryPriorityMedium, PlanEntryPriorityLow}

// Known reports whether v is one of the protocol-defined constants.
func (v PlanEntryPriority) Known() bool { return slices.Contains(PlanEntryPriorityValues, v) }

// Status of a plan entry in the execution flow.
//
// Tracks the lifecycle of each task from planning through completion.
// See protocol docs: [Plan Entries](https://agentclientprotocol.com/protocol/v2/draft/agent-plan#plan-entries)
// PlanEntryStatus also accepts values outside the listed constants; use Known to check.
type PlanEntryStatus string

const (
	PlanEntryStatusPending    PlanEntryStatus = "pending"
	PlanEntryStatusInProgress PlanEntryStatus = "in_progress"
	PlanEntryStatusCompleted  PlanEntryStatus = "completed"
	PlanEntryStatusCancelled  PlanEntryStatus = "cancelled"
)

// PlanEntryStatusValues lists the constants defined by the protocol.
var PlanEntryStatusValues = []PlanEntryStatus{PlanEntryStatusPending, PlanEntryStatusInProgress, PlanEntryStatusCompleted, PlanEntryStatusCancelled}

// Known reports whether v is one of the protocol-defined constants.
func (v PlanEntryStatus) Known() bool { return slices.Contains(PlanEntryStatusValues, v) }

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Severity hint for a session notice.
//
// @experimental
// NoticeSeverity also accepts values outside the listed constants; use Known to check.
type NoticeSeverity string

const (
	NoticeSeverityInfo    NoticeSeverity = "info"
	NoticeSeverityWarning NoticeSeverity = "warning"
	NoticeSeverityError   NoticeSeverity = "error"
)

// NoticeSeverityValues lists the constants defined by the protocol.
var NoticeSeverityValues = []NoticeSeverity{NoticeSeverityInfo, NoticeSeverityWarning, NoticeSeverityError}

// Known reports whether v is one of the protocol-defined constants.
func (v NoticeSeverity) Known() bool { return slices.Contains(NoticeSeverityValues, v) }

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Unique identifier for a context compaction within a session.
//
// @experimental
type CompactionID string

// **UNSTABLE**
//
// This capability is not part of the spec yet, and may be removed or changed at any point.
//
// Lifecycle state of a context compaction.
//
// @experimental
// CompactionStatus also accepts values outside the listed constants; use Known to check.
type CompactionStatus string

const (
	CompactionStatusInProgress CompactionStatus = "in_progress"
	CompactionStatusCompleted  CompactionStatus = "completed"
	CompactionStatusFailed     CompactionStatus = "failed"
	CompactionStatusCancelled  CompactionStatus = "cancelled"
)

// CompactionStatusValues lists the constants defined by the protocol.
var CompactionStatusValues = []CompactionStatus{CompactionStatusInProgress, CompactionStatusCompleted, CompactionStatusFailed, CompactionStatusCancelled}

// Known reports whether v is one of the protocol-defined constants.
func (v CompactionStatus) Known() bool { return slices.Contains(CompactionStatusValues, v) }

// What triggered the suggestion request.
// NesTriggerKind also accepts values outside the listed constants; use Known to check.
type NesTriggerKind string

const (
	NesTriggerKindAutomatic  NesTriggerKind = "automatic"
	NesTriggerKindDiagnostic NesTriggerKind = "diagnostic"
	NesTriggerKindManual     NesTriggerKind = "manual"
)

// NesTriggerKindValues lists the constants defined by the protocol.
var NesTriggerKindValues = []NesTriggerKind{NesTriggerKindAutomatic, NesTriggerKindDiagnostic, NesTriggerKindManual}

// Known reports whether v is one of the protocol-defined constants.
func (v NesTriggerKind) Known() bool { return slices.Contains(NesTriggerKindValues, v) }

// Severity of a diagnostic.
// NesDiagnosticSeverity also accepts values outside the listed constants; use Known to check.
type NesDiagnosticSeverity string

const (
	NesDiagnosticSeverityError       NesDiagnosticSeverity = "error"
	NesDiagnosticSeverityWarning     NesDiagnosticSeverity = "warning"
	NesDiagnosticSeverityInformation NesDiagnosticSeverity = "information"
	NesDiagnosticSeverityHint        NesDiagnosticSeverity = "hint"
)

// NesDiagnosticSeverityValues lists the constants defined by the protocol.
var NesDiagnosticSeverityValues = []NesDiagnosticSeverity{NesDiagnosticSeverityError, NesDiagnosticSeverityWarning, NesDiagnosticSeverityInformation, NesDiagnosticSeverityHint}

// Known reports whether v is one of the protocol-defined constants.
func (v NesDiagnosticSeverity) Known() bool { return slices.Contains(NesDiagnosticSeverityValues, v) }

// The reason a suggestion was rejected.
// NesRejectReason also accepts values outside the listed constants; use Known to check.
type NesRejectReason string

const (
	NesRejectReasonRejected  NesRejectReason = "rejected"
	NesRejectReasonIgnored   NesRejectReason = "ignored"
	NesRejectReasonReplaced  NesRejectReason = "replaced"
	NesRejectReasonCancelled NesRejectReason = "cancelled"
)

// NesRejectReasonValues lists the constants defined by the protocol.
var NesRejectReasonValues = []NesRejectReason{NesRejectReasonRejected, NesRejectReasonIgnored, NesRejectReasonReplaced, NesRejectReasonCancelled}

// Known reports whether v is one of the protocol-defined constants.
func (v NesRejectReason) Known() bool { return slices.Contains(NesRejectReasonValues, v) }
