// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.

package schema

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
)

var _ = json.Marshal
var _ = fmt.Errorf
var _ jsontext.Value

// A JSON-RPC request object.
type AgentRequest struct {
	// The request id used to correlate the matching response.
	ID RequestID `json:"id"`
	// The method name to invoke.
	Method string `json:"method"`
	// Method-specific request parameters.
	Params AgentRequestParams `json:"params,omitzero"`
}

// JSON RPC Request Id
//
// An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null \[1\] and Numbers SHOULD NOT contain fractional parts \[2\]
//
// The Server MUST reply with the same value in the Response object if included. This member is used to correlate the context between the two objects.
//
// \[1\] The use of Null as a value for the id member in a Request object is discouraged, because this specification uses a value of Null for Responses with an unknown id. Also, because JSON-RPC 1.0 uses an id value of Null for Notifications this could cause confusion in handling.
//
// \[2\] Fractional parts may be problematic, since many decimal fractions cannot be represented exactly as binary fractions.
// RequestID preserves the complete JSON payload, including future variants.
type RequestID struct{ raw jsontext.Value }

func (v RequestID) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *RequestID) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid RequestID JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v RequestID) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v RequestID) IsZero() bool { return len(v.raw) == 0 }
func (v RequestID) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *RequestID) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseRequestID(b []byte) (RequestID, error) {
	var v RequestID
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewRequestIDNull(value jsontext.Value) (RequestID, error) {
	if len(value) != 0 && value.Kind() != 'n' {
		return RequestID{}, fmt.Errorf("expected null for RequestID.Null")
	}
	b, err := json.Marshal(value)
	if err != nil {
		return RequestID{}, err
	}
	return RequestID{raw: b}, nil
}
func (v RequestID) AsNull() (value jsontext.Value, ok bool) {
	if v.raw.Kind() != 'n' {
		return value, false
	}
	return decodeJSON[jsontext.Value](v.raw)
}
func NewRequestIDNumber(value float64) (RequestID, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return RequestID{}, err
	}
	return RequestID{raw: b}, nil
}
func (v RequestID) AsNumber() (value float64, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	return decodeJSON[float64](v.raw)
}
func NewRequestIDString(value string) (RequestID, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return RequestID{}, err
	}
	return RequestID{raw: b}, nil
}
func (v RequestID) AsString() (value string, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	return decodeJSON[string](v.raw)
}

// A JSON-RPC response object.
// AgentResponse preserves the complete JSON payload, including future variants.
type AgentResponse struct{ raw jsontext.Value }

func (v AgentResponse) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *AgentResponse) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid AgentResponse JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v AgentResponse) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v AgentResponse) IsZero() bool { return len(v.raw) == 0 }
func (v AgentResponse) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *AgentResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseAgentResponse(b []byte) (AgentResponse, error) {
	var v AgentResponse
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewAgentResponseResult(value AgentResponseResult) (AgentResponse, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponse{}, err
	}
	return AgentResponse{raw: b}, nil
}
func (v AgentResponse) AsResult() (value AgentResponseResult, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["id"]; !ok {
		return value, false
	}
	if _, ok := fields["result"]; !ok {
		return value, false
	}
	return decodeJSON[AgentResponseResult](v.raw)
}
func NewAgentResponseError(value AgentResponseError) (AgentResponse, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponse{}, err
	}
	return AgentResponse{raw: b}, nil
}
func (v AgentResponse) AsError() (value AgentResponseError, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["id"]; !ok {
		return value, false
	}
	if _, ok := fields["error"]; !ok {
		return value, false
	}
	if raw, ok := fields["error"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[AgentResponseError](v.raw)
}

// JSON-RPC error object.
//
// Represents an error that occurred during method execution, following the
// JSON-RPC 2.0 error object specification with optional additional data.
//
// See protocol docs: [JSON-RPC Error Object](https://www.jsonrpc.org/specification#error_object)
type Error struct {
	// A number indicating the error type that occurred.
	// This must be an integer as defined in the JSON-RPC specification.
	Code ErrorCode `json:"code"`
	// A string providing a short description of the error.
	// The message should be limited to a concise single sentence.
	Message string `json:"message"`
	// Optional primitive or structured value that contains additional information about the error.
	// This may include debugging information or context-specific details.
	Data jsontext.Value `json:"data,omitzero"`
}

// A JSON-RPC notification object.
type AgentNotification struct {
	// The notification method name.
	Method string `json:"method"`
	// Method-specific notification parameters.
	Params AgentNotificationParams `json:"params,omitzero"`
}

// A JSON-RPC request object.
type ClientRequest struct {
	// The request id used to correlate the matching response.
	ID RequestID `json:"id"`
	// The method name to invoke.
	Method string `json:"method"`
	// Method-specific request parameters.
	Params ClientRequestParams `json:"params,omitzero"`
}

// A JSON-RPC response object.
// ClientResponse preserves the complete JSON payload, including future variants.
type ClientResponse struct{ raw jsontext.Value }

func (v ClientResponse) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *ClientResponse) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid ClientResponse JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v ClientResponse) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v ClientResponse) IsZero() bool { return len(v.raw) == 0 }
func (v ClientResponse) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *ClientResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseClientResponse(b []byte) (ClientResponse, error) {
	var v ClientResponse
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewClientResponseResult(value ClientResponseResult) (ClientResponse, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientResponse{}, err
	}
	return ClientResponse{raw: b}, nil
}
func (v ClientResponse) AsResult() (value ClientResponseResult, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["id"]; !ok {
		return value, false
	}
	if _, ok := fields["result"]; !ok {
		return value, false
	}
	return decodeJSON[ClientResponseResult](v.raw)
}
func NewClientResponseError(value ClientResponseError) (ClientResponse, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientResponse{}, err
	}
	return ClientResponse{raw: b}, nil
}
func (v ClientResponse) AsError() (value ClientResponseError, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["id"]; !ok {
		return value, false
	}
	if _, ok := fields["error"]; !ok {
		return value, false
	}
	if raw, ok := fields["error"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ClientResponseError](v.raw)
}

// A JSON-RPC notification object.
type ClientNotification struct {
	// The notification method name.
	Method string `json:"method"`
	// Method-specific notification parameters.
	Params ClientNotificationParams `json:"params,omitzero"`
}

// A JSON-RPC notification object.
type ProtocolLevelNotification struct {
	// The notification method name.
	Method string `json:"method"`
	// Method-specific notification parameters.
	Params *CancelRequestNotification `json:"params,omitzero"`
}

// AgentRequestParams preserves the complete JSON payload, including future variants.
type AgentRequestParams struct{ raw jsontext.Value }

func (v AgentRequestParams) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *AgentRequestParams) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid AgentRequestParams JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v AgentRequestParams) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v AgentRequestParams) IsZero() bool { return len(v.raw) == 0 }
func (v AgentRequestParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *AgentRequestParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseAgentRequestParams(b []byte) (AgentRequestParams, error) {
	var v AgentRequestParams
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewAgentRequestParamsRequestPermissionRequest(value RequestPermissionRequest) (AgentRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentRequestParams{}, err
	}
	return AgentRequestParams{raw: b}, nil
}
func (v AgentRequestParams) AsRequestPermissionRequest() (value RequestPermissionRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["title"]; !ok {
		return value, false
	}
	if _, ok := fields["options"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["title"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["options"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[RequestPermissionRequest](v.raw)
}
func NewAgentRequestParamsCreateElicitationRequest(value CreateElicitationRequest) (AgentRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentRequestParams{}, err
	}
	return AgentRequestParams{raw: b}, nil
}
func (v AgentRequestParams) AsCreateElicitationRequest() (value CreateElicitationRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	return decodeJSON[CreateElicitationRequest](v.raw)
}
func NewAgentRequestParamsConnectMCPRequest(value ConnectMCPRequest) (AgentRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentRequestParams{}, err
	}
	return AgentRequestParams{raw: b}, nil
}
func (v AgentRequestParams) AsConnectMCPRequest() (value ConnectMCPRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["serverId"]; !ok {
		return value, false
	}
	if raw, ok := fields["serverId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ConnectMCPRequest](v.raw)
}
func NewAgentRequestParamsMessageMCPRequest(value MessageMCPRequest) (AgentRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentRequestParams{}, err
	}
	return AgentRequestParams{raw: b}, nil
}
func (v AgentRequestParams) AsMessageMCPRequest() (value MessageMCPRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["connectionId"]; !ok {
		return value, false
	}
	if _, ok := fields["method"]; !ok {
		return value, false
	}
	if raw, ok := fields["connectionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["method"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[MessageMCPRequest](v.raw)
}
func NewAgentRequestParamsDisconnectMCPRequest(value DisconnectMCPRequest) (AgentRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentRequestParams{}, err
	}
	return AgentRequestParams{raw: b}, nil
}
func (v AgentRequestParams) AsDisconnectMCPRequest() (value DisconnectMCPRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["connectionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["connectionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[DisconnectMCPRequest](v.raw)
}
func NewAgentRequestParamsExtRequest(value ExtRequest) (AgentRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentRequestParams{}, err
	}
	return AgentRequestParams{raw: b}, nil
}
func (v AgentRequestParams) AsExtRequest() (value ExtRequest, ok bool) {
	return decodeJSON[ExtRequest](v.raw)
}

type AgentResponseResult struct {
	// The id of the request this response answers.
	ID RequestID `json:"id"`
	// Method-specific response data.
	Result AgentResponseResultResult `json:"result"`
}

type AgentResponseError struct {
	// The id of the request this response answers.
	ID RequestID `json:"id"`
	// Method-specific error data.
	Error Error `json:"error"`
}

// AgentNotificationParams preserves the complete JSON payload, including future variants.
type AgentNotificationParams struct{ raw jsontext.Value }

func (v AgentNotificationParams) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *AgentNotificationParams) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid AgentNotificationParams JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v AgentNotificationParams) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v AgentNotificationParams) IsZero() bool { return len(v.raw) == 0 }
func (v AgentNotificationParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *AgentNotificationParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseAgentNotificationParams(b []byte) (AgentNotificationParams, error) {
	var v AgentNotificationParams
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewAgentNotificationParamsUpdateSessionNotification(value UpdateSessionNotification) (AgentNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentNotificationParams{}, err
	}
	return AgentNotificationParams{raw: b}, nil
}
func (v AgentNotificationParams) AsUpdateSessionNotification() (value UpdateSessionNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["update"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["update"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[UpdateSessionNotification](v.raw)
}
func NewAgentNotificationParamsCompleteElicitationNotification(value CompleteElicitationNotification) (AgentNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentNotificationParams{}, err
	}
	return AgentNotificationParams{raw: b}, nil
}
func (v AgentNotificationParams) AsCompleteElicitationNotification() (value CompleteElicitationNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["elicitationId"]; !ok {
		return value, false
	}
	if raw, ok := fields["elicitationId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[CompleteElicitationNotification](v.raw)
}
func NewAgentNotificationParamsMessageMCPNotification(value MessageMCPNotification) (AgentNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentNotificationParams{}, err
	}
	return AgentNotificationParams{raw: b}, nil
}
func (v AgentNotificationParams) AsMessageMCPNotification() (value MessageMCPNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["connectionId"]; !ok {
		return value, false
	}
	if _, ok := fields["method"]; !ok {
		return value, false
	}
	if raw, ok := fields["connectionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["method"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[MessageMCPNotification](v.raw)
}
func NewAgentNotificationParamsExtNotification(value ExtNotification) (AgentNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentNotificationParams{}, err
	}
	return AgentNotificationParams{raw: b}, nil
}
func (v AgentNotificationParams) AsExtNotification() (value ExtNotification, ok bool) {
	return decodeJSON[ExtNotification](v.raw)
}

// ClientRequestParams preserves the complete JSON payload, including future variants.
type ClientRequestParams struct{ raw jsontext.Value }

func (v ClientRequestParams) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *ClientRequestParams) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid ClientRequestParams JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v ClientRequestParams) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v ClientRequestParams) IsZero() bool { return len(v.raw) == 0 }
func (v ClientRequestParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *ClientRequestParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseClientRequestParams(b []byte) (ClientRequestParams, error) {
	var v ClientRequestParams
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewClientRequestParamsInitializeRequest(value InitializeRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsInitializeRequest() (value InitializeRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["protocolVersion"]; !ok {
		return value, false
	}
	if _, ok := fields["info"]; !ok {
		return value, false
	}
	if raw, ok := fields["protocolVersion"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["info"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["capabilities"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[InitializeRequest](v.raw)
}
func NewClientRequestParamsLoginAuthRequest(value LoginAuthRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsLoginAuthRequest() (value LoginAuthRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["methodId"]; !ok {
		return value, false
	}
	if raw, ok := fields["methodId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[LoginAuthRequest](v.raw)
}
func NewClientRequestParamsListProvidersRequest(value ListProvidersRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsListProvidersRequest() (value ListProvidersRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[ListProvidersRequest](v.raw)
}
func NewClientRequestParamsSetProviderRequest(value SetProviderRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsSetProviderRequest() (value SetProviderRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["providerId"]; !ok {
		return value, false
	}
	if _, ok := fields["apiType"]; !ok {
		return value, false
	}
	if _, ok := fields["baseUrl"]; !ok {
		return value, false
	}
	if raw, ok := fields["providerId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["apiType"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["baseUrl"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["headers"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[SetProviderRequest](v.raw)
}
func NewClientRequestParamsDisableProviderRequest(value DisableProviderRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsDisableProviderRequest() (value DisableProviderRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["providerId"]; !ok {
		return value, false
	}
	if raw, ok := fields["providerId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[DisableProviderRequest](v.raw)
}
func NewClientRequestParamsLogoutAuthRequest(value LogoutAuthRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsLogoutAuthRequest() (value LogoutAuthRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[LogoutAuthRequest](v.raw)
}
func NewClientRequestParamsNewSessionRequest(value NewSessionRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsNewSessionRequest() (value NewSessionRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["cwd"]; !ok {
		return value, false
	}
	if raw, ok := fields["cwd"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["additionalDirectories"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["mcpServers"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[NewSessionRequest](v.raw)
}
func NewClientRequestParamsListSessionsRequest(value ListSessionsRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsListSessionsRequest() (value ListSessionsRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[ListSessionsRequest](v.raw)
}
func NewClientRequestParamsDeleteSessionRequest(value DeleteSessionRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsDeleteSessionRequest() (value DeleteSessionRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[DeleteSessionRequest](v.raw)
}
func NewClientRequestParamsForkSessionRequest(value ForkSessionRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsForkSessionRequest() (value ForkSessionRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["cwd"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["cwd"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["additionalDirectories"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["mcpServers"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ForkSessionRequest](v.raw)
}
func NewClientRequestParamsResumeSessionRequest(value ResumeSessionRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsResumeSessionRequest() (value ResumeSessionRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["cwd"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["cwd"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["additionalDirectories"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["mcpServers"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ResumeSessionRequest](v.raw)
}
func NewClientRequestParamsCloseSessionRequest(value CloseSessionRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsCloseSessionRequest() (value CloseSessionRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[CloseSessionRequest](v.raw)
}
func NewClientRequestParamsSetSessionConfigOptionRequest(value SetSessionConfigOptionRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsSetSessionConfigOptionRequest() (value SetSessionConfigOptionRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	return decodeJSON[SetSessionConfigOptionRequest](v.raw)
}
func NewClientRequestParamsPromptRequest(value PromptRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsPromptRequest() (value PromptRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["prompt"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["prompt"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[PromptRequest](v.raw)
}
func NewClientRequestParamsStartNesRequest(value StartNesRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsStartNesRequest() (value StartNesRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[StartNesRequest](v.raw)
}
func NewClientRequestParamsSuggestNesRequest(value SuggestNesRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsSuggestNesRequest() (value SuggestNesRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["uri"]; !ok {
		return value, false
	}
	if _, ok := fields["version"]; !ok {
		return value, false
	}
	if _, ok := fields["position"]; !ok {
		return value, false
	}
	if _, ok := fields["triggerKind"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["uri"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["version"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["position"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["triggerKind"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[SuggestNesRequest](v.raw)
}
func NewClientRequestParamsCloseNesRequest(value CloseNesRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsCloseNesRequest() (value CloseNesRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[CloseNesRequest](v.raw)
}
func NewClientRequestParamsMessageMCPRequest(value MessageMCPRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsMessageMCPRequest() (value MessageMCPRequest, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["connectionId"]; !ok {
		return value, false
	}
	if _, ok := fields["method"]; !ok {
		return value, false
	}
	if raw, ok := fields["connectionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["method"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[MessageMCPRequest](v.raw)
}
func NewClientRequestParamsExtRequest(value ExtRequest) (ClientRequestParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientRequestParams{}, err
	}
	return ClientRequestParams{raw: b}, nil
}
func (v ClientRequestParams) AsExtRequest() (value ExtRequest, ok bool) {
	return decodeJSON[ExtRequest](v.raw)
}

type ClientResponseResult struct {
	// The id of the request this response answers.
	ID RequestID `json:"id"`
	// Method-specific response data.
	Result ClientResponseResultResult `json:"result"`
}

type ClientResponseError struct {
	// The id of the request this response answers.
	ID RequestID `json:"id"`
	// Method-specific error data.
	Error Error `json:"error"`
}

// ClientNotificationParams preserves the complete JSON payload, including future variants.
type ClientNotificationParams struct{ raw jsontext.Value }

func (v ClientNotificationParams) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *ClientNotificationParams) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid ClientNotificationParams JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v ClientNotificationParams) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v ClientNotificationParams) IsZero() bool { return len(v.raw) == 0 }
func (v ClientNotificationParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *ClientNotificationParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseClientNotificationParams(b []byte) (ClientNotificationParams, error) {
	var v ClientNotificationParams
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewClientNotificationParamsCancelSessionNotification(value CancelSessionNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsCancelSessionNotification() (value CancelSessionNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[CancelSessionNotification](v.raw)
}
func NewClientNotificationParamsDidOpenDocumentNotification(value DidOpenDocumentNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsDidOpenDocumentNotification() (value DidOpenDocumentNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["uri"]; !ok {
		return value, false
	}
	if _, ok := fields["languageId"]; !ok {
		return value, false
	}
	if _, ok := fields["version"]; !ok {
		return value, false
	}
	if _, ok := fields["text"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["uri"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["languageId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["version"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["text"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[DidOpenDocumentNotification](v.raw)
}
func NewClientNotificationParamsDidChangeDocumentNotification(value DidChangeDocumentNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsDidChangeDocumentNotification() (value DidChangeDocumentNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["uri"]; !ok {
		return value, false
	}
	if _, ok := fields["version"]; !ok {
		return value, false
	}
	if _, ok := fields["contentChanges"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["uri"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["version"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["contentChanges"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[DidChangeDocumentNotification](v.raw)
}
func NewClientNotificationParamsDidCloseDocumentNotification(value DidCloseDocumentNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsDidCloseDocumentNotification() (value DidCloseDocumentNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["uri"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["uri"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[DidCloseDocumentNotification](v.raw)
}
func NewClientNotificationParamsDidSaveDocumentNotification(value DidSaveDocumentNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsDidSaveDocumentNotification() (value DidSaveDocumentNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["uri"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["uri"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[DidSaveDocumentNotification](v.raw)
}
func NewClientNotificationParamsDidFocusDocumentNotification(value DidFocusDocumentNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsDidFocusDocumentNotification() (value DidFocusDocumentNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["uri"]; !ok {
		return value, false
	}
	if _, ok := fields["version"]; !ok {
		return value, false
	}
	if _, ok := fields["position"]; !ok {
		return value, false
	}
	if _, ok := fields["visibleRange"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["uri"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["version"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["position"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["visibleRange"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[DidFocusDocumentNotification](v.raw)
}
func NewClientNotificationParamsAcceptNesNotification(value AcceptNesNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsAcceptNesNotification() (value AcceptNesNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["suggestionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["suggestionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[AcceptNesNotification](v.raw)
}
func NewClientNotificationParamsRejectNesNotification(value RejectNesNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsRejectNesNotification() (value RejectNesNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if _, ok := fields["suggestionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["suggestionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[RejectNesNotification](v.raw)
}
func NewClientNotificationParamsMessageMCPNotification(value MessageMCPNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsMessageMCPNotification() (value MessageMCPNotification, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["connectionId"]; !ok {
		return value, false
	}
	if _, ok := fields["method"]; !ok {
		return value, false
	}
	if raw, ok := fields["connectionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["method"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[MessageMCPNotification](v.raw)
}
func NewClientNotificationParamsExtNotification(value ExtNotification) (ClientNotificationParams, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientNotificationParams{}, err
	}
	return ClientNotificationParams{raw: b}, nil
}
func (v ClientNotificationParams) AsExtNotification() (value ExtNotification, ok bool) {
	return decodeJSON[ExtNotification](v.raw)
}

// AgentResponseResultResult preserves the complete JSON payload, including future variants.
type AgentResponseResultResult struct{ raw jsontext.Value }

func (v AgentResponseResultResult) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *AgentResponseResultResult) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid AgentResponseResultResult JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v AgentResponseResultResult) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v AgentResponseResultResult) IsZero() bool { return len(v.raw) == 0 }
func (v AgentResponseResultResult) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *AgentResponseResultResult) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseAgentResponseResultResult(b []byte) (AgentResponseResultResult, error) {
	var v AgentResponseResultResult
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewAgentResponseResultResultInitializeResponse(value InitializeResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsInitializeResponse() (value InitializeResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["protocolVersion"]; !ok {
		return value, false
	}
	if _, ok := fields["info"]; !ok {
		return value, false
	}
	if raw, ok := fields["protocolVersion"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["info"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["capabilities"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["authMethods"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[InitializeResponse](v.raw)
}
func NewAgentResponseResultResultLoginAuthResponse(value LoginAuthResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsLoginAuthResponse() (value LoginAuthResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[LoginAuthResponse](v.raw)
}
func NewAgentResponseResultResultListProvidersResponse(value ListProvidersResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsListProvidersResponse() (value ListProvidersResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["providers"]; !ok {
		return value, false
	}
	if raw, ok := fields["providers"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ListProvidersResponse](v.raw)
}
func NewAgentResponseResultResultSetProviderResponse(value SetProviderResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsSetProviderResponse() (value SetProviderResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[SetProviderResponse](v.raw)
}
func NewAgentResponseResultResultDisableProviderResponse(value DisableProviderResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsDisableProviderResponse() (value DisableProviderResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[DisableProviderResponse](v.raw)
}
func NewAgentResponseResultResultLogoutAuthResponse(value LogoutAuthResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsLogoutAuthResponse() (value LogoutAuthResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[LogoutAuthResponse](v.raw)
}
func NewAgentResponseResultResultNewSessionResponse(value NewSessionResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsNewSessionResponse() (value NewSessionResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["configOptions"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[NewSessionResponse](v.raw)
}
func NewAgentResponseResultResultListSessionsResponse(value ListSessionsResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsListSessionsResponse() (value ListSessionsResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessions"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessions"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ListSessionsResponse](v.raw)
}
func NewAgentResponseResultResultDeleteSessionResponse(value DeleteSessionResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsDeleteSessionResponse() (value DeleteSessionResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[DeleteSessionResponse](v.raw)
}
func NewAgentResponseResultResultForkSessionResponse(value ForkSessionResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsForkSessionResponse() (value ForkSessionResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	if raw, ok := fields["configOptions"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ForkSessionResponse](v.raw)
}
func NewAgentResponseResultResultResumeSessionResponse(value ResumeSessionResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsResumeSessionResponse() (value ResumeSessionResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if raw, ok := fields["configOptions"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ResumeSessionResponse](v.raw)
}
func NewAgentResponseResultResultCloseSessionResponse(value CloseSessionResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsCloseSessionResponse() (value CloseSessionResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[CloseSessionResponse](v.raw)
}
func NewAgentResponseResultResultSetSessionConfigOptionResponse(value SetSessionConfigOptionResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsSetSessionConfigOptionResponse() (value SetSessionConfigOptionResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["configOptions"]; !ok {
		return value, false
	}
	if raw, ok := fields["configOptions"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[SetSessionConfigOptionResponse](v.raw)
}
func NewAgentResponseResultResultPromptResponse(value PromptResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsPromptResponse() (value PromptResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["messageId"]; !ok {
		return value, false
	}
	if raw, ok := fields["messageId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[PromptResponse](v.raw)
}
func NewAgentResponseResultResultStartNesResponse(value StartNesResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsStartNesResponse() (value StartNesResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["sessionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["sessionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[StartNesResponse](v.raw)
}
func NewAgentResponseResultResultSuggestNesResponse(value SuggestNesResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsSuggestNesResponse() (value SuggestNesResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["suggestions"]; !ok {
		return value, false
	}
	if raw, ok := fields["suggestions"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[SuggestNesResponse](v.raw)
}
func NewAgentResponseResultResultCloseNesResponse(value CloseNesResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsCloseNesResponse() (value CloseNesResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[CloseNesResponse](v.raw)
}
func NewAgentResponseResultResultExtResponse(value ExtResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsExtResponse() (value ExtResponse, ok bool) {
	return decodeJSON[ExtResponse](v.raw)
}
func NewAgentResponseResultResultMessageMCPResponse(value MessageMCPResponse) (AgentResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return AgentResponseResultResult{}, err
	}
	return AgentResponseResultResult{raw: b}, nil
}
func (v AgentResponseResultResult) AsMessageMCPResponse() (value MessageMCPResponse, ok bool) {
	return decodeJSON[MessageMCPResponse](v.raw)
}

// ClientResponseResultResult preserves the complete JSON payload, including future variants.
type ClientResponseResultResult struct{ raw jsontext.Value }

func (v ClientResponseResultResult) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *ClientResponseResultResult) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid ClientResponseResultResult JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v ClientResponseResultResult) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v ClientResponseResultResult) IsZero() bool { return len(v.raw) == 0 }
func (v ClientResponseResultResult) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *ClientResponseResultResult) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseClientResponseResultResult(b []byte) (ClientResponseResultResult, error) {
	var v ClientResponseResultResult
	err := json.Unmarshal(b, &v)
	return v, err
}
func NewClientResponseResultResultRequestPermissionResponse(value RequestPermissionResponse) (ClientResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientResponseResultResult{}, err
	}
	return ClientResponseResultResult{raw: b}, nil
}
func (v ClientResponseResultResult) AsRequestPermissionResponse() (value RequestPermissionResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["outcome"]; !ok {
		return value, false
	}
	if raw, ok := fields["outcome"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[RequestPermissionResponse](v.raw)
}
func NewClientResponseResultResultCreateElicitationResponse(value CreateElicitationResponse) (ClientResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientResponseResultResult{}, err
	}
	return ClientResponseResultResult{raw: b}, nil
}
func (v ClientResponseResultResult) AsCreateElicitationResponse() (value CreateElicitationResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	return decodeJSON[CreateElicitationResponse](v.raw)
}
func NewClientResponseResultResultConnectMCPResponse(value ConnectMCPResponse) (ClientResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientResponseResultResult{}, err
	}
	return ClientResponseResultResult{raw: b}, nil
}
func (v ClientResponseResultResult) AsConnectMCPResponse() (value ConnectMCPResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	if _, ok := fields["connectionId"]; !ok {
		return value, false
	}
	if raw, ok := fields["connectionId"]; ok && raw.Kind() == 'n' {
		return value, false
	}
	return decodeJSON[ConnectMCPResponse](v.raw)
}
func NewClientResponseResultResultDisconnectMCPResponse(value DisconnectMCPResponse) (ClientResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientResponseResultResult{}, err
	}
	return ClientResponseResultResult{raw: b}, nil
}
func (v ClientResponseResultResult) AsDisconnectMCPResponse() (value DisconnectMCPResponse, ok bool) {
	if v.raw.Kind() == 'n' || len(v.raw) == 0 {
		return value, false
	}
	var fields map[string]jsontext.Value
	if json.Unmarshal(v.raw, &fields) != nil || fields == nil {
		return value, false
	}
	return decodeJSON[DisconnectMCPResponse](v.raw)
}
func NewClientResponseResultResultMessageMCPResponse(value MessageMCPResponse) (ClientResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientResponseResultResult{}, err
	}
	return ClientResponseResultResult{raw: b}, nil
}
func (v ClientResponseResultResult) AsMessageMCPResponse() (value MessageMCPResponse, ok bool) {
	return decodeJSON[MessageMCPResponse](v.raw)
}
func NewClientResponseResultResultExtResponse(value ExtResponse) (ClientResponseResultResult, error) {
	b, err := json.Marshal(value)
	if err != nil {
		return ClientResponseResultResult{}, err
	}
	return ClientResponseResultResult{raw: b}, nil
}
func (v ClientResponseResultResult) AsExtResponse() (value ExtResponse, ok bool) {
	return decodeJSON[ExtResponse](v.raw)
}
