// Package tsgen generates Go wire types from the ACP TypeScript schema subset.
package tsgen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/ironpark/go-acp/internal/cmd/schema/tsdef"
)

type generator struct {
	defs    map[string]*tsdef.Type
	pending []tsdef.Definition
	names   map[string]bool
	out     bytes.Buffer
}

// Generate emits deterministic Go declarations. Unknown JSON payloads are kept
// as jsontext.Value, so custom/future variants survive a decode/encode cycle.
func Generate(schema *tsdef.Schema, pkg string) ([]byte, error) {
	if !token.IsIdentifier(pkg) || token.Lookup(pkg).IsKeyword() || pkg == "_" {
		return nil, fmt.Errorf("invalid package name %q", pkg)
	}
	g := &generator{defs: map[string]*tsdef.Type{}, names: map[string]bool{}}
	for _, d := range schema.Types {
		name := Name(d.Name)
		if g.names[name] {
			return nil, fmt.Errorf("duplicate Go type %s", name)
		}
		g.names[name] = true
		g.defs[d.Name] = d.Type
		d.Name = name
		g.pending = append(g.pending, d)
	}
	if len(schema.Validators) > 0 {
		g.write("// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.\n\npackage %s\n\nimport (\"bytes\";\"errors\";\"math\";\"net/url\";\"regexp\";\"slices\";\"strings\";\"time\";\"unicode/utf8\";\"encoding/json/v2\";\"encoding/json/jsontext\";\"fmt\")\n", pkg)
	} else {
		g.write("// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.\n\npackage %s\n\nimport (\"encoding/json/v2\"; \"encoding/json/jsontext\"; \"fmt\"; \"slices\")\n", pkg)
	}
	g.write("var _ = json.Marshal\nvar _ = fmt.Errorf\nvar _ = slices.Contains[[]string]\n\nfunc decodeJSON[T any](raw jsontext.Value) (T, bool) { var value T; if err := json.Unmarshal(raw, &value); err != nil { return value, false }; return value, true }\n\n")

	for _, c := range schema.Constants {
		if len(c.Members) > 0 {
			for _, m := range c.Members {
				name := Name(c.Name) + Name(m.Name)
				if g.names[name] {
					return nil, fmt.Errorf("duplicate Go declaration %s", name)
				}
				g.names[name] = true
				g.write("const %s = %s\n", name, m.Value)
			}
		} else {
			name := Name(c.Name)
			if c.Name == "PROTOCOL_VERSION" {
				name = "CurrentProtocolVersion"
			}
			if g.names[name] {
				return nil, fmt.Errorf("duplicate Go declaration %s", name)
			}
			g.names[name] = true
			g.write("const %s = %s\n", name, c.Value)
		}
	}
	for i := 0; i < len(g.pending); i++ {
		if err := g.definition(g.pending[i]); err != nil {
			return nil, fmt.Errorf("%s: %w", g.pending[i].Name, err)
		}
	}
	if err := g.zod(schema); err != nil {
		return nil, err
	}
	result, err := format.Source(g.out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	return result, nil
}
func (g *generator) write(f string, a ...any) { fmt.Fprintf(&g.out, f, a...) }
func comment(s string) string {
	if s == "" {
		return ""
	}
	return "// " + strings.ReplaceAll(s, "\n", "\n// ") + "\n"
}

// Name maps SDK identifiers to exported Go identifiers using common initialisms.
func Name(s string) string {
	var words []string
	var word []rune
	rs := []rune(s)
	flush := func() {
		if len(word) > 0 {
			words = append(words, string(word))
			word = nil
		}
	}
	for i, r := range rs {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			flush()
			continue
		}
		if len(word) > 0 && unicode.IsUpper(r) && (unicode.IsLower(rs[i-1]) || (i+1 < len(rs) && unicode.IsLower(rs[i+1]) && unicode.IsUpper(rs[i-1]))) {
			flush()
		}
		word = append(word, r)
	}
	flush()
	for i, w := range words {
		lower := strings.ToLower(w)
		switch lower {
		case "id", "rpc", "url", "uri", "http", "https", "json", "api", "mcp", "acp":
			words[i] = strings.ToUpper(lower)
		default:
			runes := []rune(lower)
			runes[0] = unicode.ToUpper(runes[0])
			words[i] = string(runes)
		}
	}
	result := strings.Join(words, "")
	if result == "" {
		return "Empty"
	}
	if unicode.IsDigit([]rune(result)[0]) {
		result = "Value" + result
	}
	return result
}
func (g *generator) add(name string, t *tsdef.Type) string {
	base := name
	for i := 2; g.names[name]; i++ {
		name = fmt.Sprintf("%s%d", base, i)
	}
	g.names[name] = true
	g.pending = append(g.pending, tsdef.Definition{Name: name, Type: t})
	return name
}
func nullable(t *tsdef.Type) (*tsdef.Type, bool) {
	if t.Kind != "union" {
		return t, t.Kind == "null"
	}
	var members []*tsdef.Type
	null := false
	for _, m := range t.Members {
		if m.Kind == "null" {
			null = true
		} else {
			members = append(members, m)
		}
	}
	if len(members) == 1 {
		return members[0], null
	}
	return &tsdef.Type{Kind: "union", Members: members}, null
}
func literals(t *tsdef.Type) (string, bool) {
	if t.Kind == "literal" {
		if strings.HasPrefix(t.Literal, "\"") || strings.HasPrefix(t.Literal, "'") {
			return "string", true
		}
		if t.Literal == "true" || t.Literal == "false" {
			return "bool", true
		}
		return "float64", true
	}
	if t.Kind != "union" || len(t.Members) == 0 {
		return "", false
	}
	kind := ""
	for _, m := range t.Members {
		k, ok := literals(m)
		if !ok || (kind != "" && k != kind) {
			return "", false
		}
		kind = k
	}
	return kind, true
}

// openEnum reports literal unions that also admit any value of the same
// primitive type, such as "a" | "b" | string. The primitive member is returned
// so its numeric hint can be used for the Go base type.
func openEnum(t *tsdef.Type) (base *tsdef.Type, members []*tsdef.Type, ok bool) {
	if t.Kind != "union" {
		return nil, nil, false
	}
	kind := ""
	for _, m := range t.Members {
		switch m.Kind {
		case "literal":
			k, _ := literals(m)
			if kind != "" && k != kind {
				return nil, nil, false
			}
			kind = k
			members = append(members, m)
		case "string", "number", "boolean":
			if base != nil {
				return nil, nil, false
			}
			base = m
		default:
			return nil, nil, false
		}
	}
	if base == nil || len(members) == 0 {
		return nil, nil, false
	}
	baseKind := map[string]string{"string": "string", "number": "float64", "boolean": "bool"}[base.Kind]
	if baseKind != kind {
		return nil, nil, false
	}
	return base, members, true
}

// literalNames overrides constant names for literals that cannot be derived
// from their value, keyed by TypeScript type name.
var literalNames = map[string]map[string]string{
	"ErrorCode": {
		"-32700": "ParseError",
		"-32600": "InvalidRequest",
		"-32601": "MethodNotFound",
		"-32602": "InvalidParams",
		"-32603": "InternalError",
		"-32800": "RequestCancelled",
		"-32000": "AuthenticationRequired",
		"-32002": "ResourceNotFound",
	},
}

func (g *generator) expr(t *tsdef.Type, hint string) (string, error) {
	t, isNull := nullable(t)
	var out string
	switch t.Kind {
	case "ref":
		if _, ok := g.defs[t.Name]; !ok {
			return "", fmt.Errorf("unresolved type %s", t.Name)
		}
		out = Name(t.Name)
	case "string":
		out = "string"
	case "number":
		out = "float64"
		if t.Number != "" {
			out = t.Number
		}
	case "boolean":
		out = "bool"
	case "unknown", "any", "null", "never":
		out = "jsontext.Value"
	case "literal":
		out, _ = literals(t)
	case "array":
		e, err := g.expr(t.Element, hint+"Item")
		if err != nil {
			return "", err
		}
		out = "[]" + e
	case "object":
		if len(t.Fields) == 0 {
			if t.Element == nil {
				out = "map[string]jsontext.Value"
			} else {
				e, err := g.expr(t.Element, hint+"Value")
				if err != nil {
					return "", err
				}
				out = "map[string]" + e
			}
		} else {
			out = g.add(hint, t)
		}
	case "union", "intersection":
		out = g.add(hint, t)
	default:
		return "", fmt.Errorf("unsupported IR type %s", t.Kind)
	}
	if isNull && out != "jsontext.Value" {
		out = "*" + out
	}
	return out, nil
}
func (g *generator) definition(d tsdef.Definition) error {
	t := d.Type
	g.write("\n%s", comment(d.Comment))
	if kind, ok := literals(t); ok {
		members := t.Members
		if t.Kind == "literal" {
			members = []*tsdef.Type{t}
		}
		return g.enum(d.Name, kind, members, false)
	}
	if base, members, ok := openEnum(t); ok {
		kind, _ := literals(members[0])
		if base.Kind == "number" && base.Number != "" {
			kind = base.Number
		}
		return g.enum(d.Name, kind, members, true)
	}
	if t.Kind == "intersection" {
		expanded, err := g.expand(t, map[string]bool{})
		if err != nil {
			return err
		}
		t = expanded
	}
	switch t.Kind {
	case "object":
		return g.object(d.Name, t)
	case "union":
		nonnull, isNull := nullable(t)
		if isNull && nonnull.Kind != "union" {
			expr, err := g.expr(t, d.Name+"Value")
			if err != nil {
				return err
			}
			g.write("type %s = %s\n", d.Name, expr)
			return nil
		}
		return g.union(d.Name, t)
	default:
		expr, err := g.expr(t, d.Name+"Value")
		if err != nil {
			return err
		}
		g.write("type %s = %s\n", d.Name, expr)
		return nil
	}
}

// enum emits a named scalar type with one constant per literal. Open enums
// also accept values outside the listed constants.
func (g *generator) enum(typeName, kind string, members []*tsdef.Type, open bool) error {
	if open {
		g.write("// %s also accepts values outside the listed constants; use Known to check.\n", typeName)
	}
	g.write("type %s %s\n", typeName, kind)
	if open {
		if err := g.reserve(typeName + "Values"); err != nil {
			return err
		}
	}
	used := map[string]bool{}
	var names []string
	g.write("const (\n")
	for _, m := range members {
		value := m.Literal
		label := value
		if kind == "string" {
			var err error
			label, err = strconv.Unquote(value)
			if err != nil {
				return err
			}
		}
		if override, ok := literalNames[typeName][value]; ok {
			label = override
		}
		name := typeName + Name(label)
		if used[name] || g.names[name] {
			return fmt.Errorf("enum constant collision %s", name)
		}
		used[name] = true
		g.names[name] = true
		names = append(names, name)
		g.write("%s %s = %s\n", name, typeName, value)
	}
	g.write(")\n")
	if open {
		g.write("// %sValues lists the constants defined by the protocol.\n", typeName)
		g.write("var %sValues = []%s{%s}\n", typeName, typeName, strings.Join(names, ", "))
		g.write("// Known reports whether v is one of the protocol-defined constants.\n")
		g.write("func (v %s) Known() bool { return slices.Contains(%sValues, v) }\n", typeName, typeName)
	}
	return nil
}

// expand distributes intersections over unions and merges object members.
func (g *generator) expand(t *tsdef.Type, seen map[string]bool) (*tsdef.Type, error) {
	if t.Kind == "ref" {
		if seen[t.Name] {
			return nil, fmt.Errorf("cyclic intersection through %s", t.Name)
		}
		target, ok := g.defs[t.Name]
		if !ok {
			return nil, fmt.Errorf("unresolved type %s", t.Name)
		}
		seen[t.Name] = true
		out, err := g.expand(target, seen)
		delete(seen, t.Name)
		return out, err
	}
	if t.Kind == "union" {
		var members []*tsdef.Type
		for _, member := range t.Members {
			expanded, err := g.expand(member, seen)
			if err != nil {
				return nil, err
			}
			if expanded.Kind == "union" {
				members = append(members, expanded.Members...)
			} else {
				members = append(members, expanded)
			}
		}
		return &tsdef.Type{Kind: "union", Members: members}, nil
	}
	if t.Kind != "intersection" {
		return t, nil
	}
	variants := []*tsdef.Type{{Kind: "object"}}
	for _, member := range t.Members {
		m, err := g.expand(member, seen)
		if err != nil {
			return nil, err
		}
		alternatives := []*tsdef.Type{m}
		if m.Kind == "union" {
			alternatives = m.Members
		}
		var next []*tsdef.Type
		for _, base := range variants {
			for _, alt := range alternatives {
				a, err := g.expand(alt, seen)
				if err != nil {
					return nil, err
				}
				if a.Kind != "object" {
					return nil, fmt.Errorf("intersection member is %s, expected object", a.Kind)
				}
				merged := &tsdef.Type{Kind: "object", Fields: append([]tsdef.Field(nil), base.Fields...), Element: base.Element}
				if a.Element != nil {
					merged.Element = a.Element
				}
				for _, f := range a.Fields {
					found := false
					for i, old := range merged.Fields {
						if old.Name == f.Name {
							found = true
							f.Optional = f.Optional && old.Optional
							if !reflect.DeepEqual(f.Type, old.Type) {
								if f.Type.Kind == "literal" && old.Type.Kind == "string" {
								} else if old.Type.Kind == "literal" && f.Type.Kind == "string" {
									f.Type = old.Type
								} else {
									return nil, fmt.Errorf("unsupported intersection for property %s", f.Name)
								}
							}
							merged.Fields[i] = f
							break
						}
					}
					if !found {
						merged.Fields = append(merged.Fields, f)
					}
				}
				next = append(next, merged)
			}
		}
		variants = next
	}
	if len(variants) == 1 {
		return variants[0], nil
	}
	return &tsdef.Type{Kind: "union", Members: variants}, nil
}
func (g *generator) object(name string, t *tsdef.Type) error {
	if len(t.Fields) == 0 {
		expr, err := g.expr(t, name+"Value")
		if err != nil {
			return err
		}
		g.write("type %s = %s\n", name, expr)
		return nil
	}
	g.write("type %s struct {\n", name)
	names := map[string]bool{}
	for _, f := range t.Fields {
		field := Name(f.Name)
		if field == "AdditionalProperties" && t.Element != nil {
			return fmt.Errorf("reserved field %s", field)
		}
		if names[field] {
			return fmt.Errorf("field collision %s", field)
		}
		names[field] = true
		expr, err := g.expr(f.Type, name+field)
		if err != nil {
			return err
		}
		if f.Optional {
			// omitzero already distinguishes nil collections from empty ones, so
			// optional slices and maps do not need a pointer. Optional null and
			// absence share the nil representation.
			if collection(strings.TrimPrefix(expr, "*")) {
				expr = strings.TrimPrefix(expr, "*")
			} else if !strings.HasPrefix(expr, "*") && expr != "jsontext.Value" {
				expr = "*" + expr
			}
		}
		tag := f.Name
		if f.Optional {
			tag += ",omitzero"
		}
		g.write("%s%s %s `json:%q`\n", comment(f.Comment), field, expr, tag)
	}
	if t.Element != nil {
		element, err := g.expr(t.Element, name+"AdditionalProperty")
		if err != nil {
			return err
		}
		g.write("AdditionalProperties map[string]%s `json:\",embed\"`\n", element)
	}
	g.write("}\n")
	return nil
}
func collection(expr string) bool {
	return strings.HasPrefix(expr, "[]") || strings.HasPrefix(expr, "map[")
}
func (g *generator) union(name string, t *tsdef.Type) error {
	if err := g.reserve("Parse" + name); err != nil {
		return err
	}
	g.write("// %s preserves the complete JSON payload, including future variants.\n", name)
	g.write("type %s struct { raw jsontext.Value }\n", name)
	g.write("func (v %s) MarshalJSON() ([]byte,error) {if len(v.raw)==0{return []byte(\"null\"),nil};return v.raw.Clone(),nil}\n", name)
	g.write("func (v *%s) UnmarshalJSON(b []byte) error {if !jsontext.Value(b).IsValid(){return fmt.Errorf(\"invalid %s JSON\")};v.raw=jsontext.Value(b).Clone();return nil}\n", name, name)
	g.write("func (v %s) RawJSON() jsontext.Value {return v.raw.Clone()}\n", name)
	g.write("func (v %s) MarshalJSONTo(enc *jsontext.Encoder) error {if len(v.raw)==0{return enc.WriteValue(jsontext.Value(\"null\"))};return enc.WriteValue(v.raw)}\n", name)
	g.write("func (v *%s) UnmarshalJSONFrom(dec *jsontext.Decoder) error {raw,err:=dec.ReadValue();if err!=nil{return err};v.raw=raw.Clone();return nil}\n", name)
	g.write("func Parse%s(b []byte) (%s,error) {var v %s;err:=json.Unmarshal(b,&v);return v,err}\n", name, name, name)
	used := map[string]bool{}
	for i, m := range t.Members {
		label := "Variant" + strconv.Itoa(i+1)
		expanded, err := g.expand(m, map[string]bool{})
		if err != nil {
			return err
		}
		if m.Kind == "ref" {
			label = Name(m.Name)
		}
		var tags []tsdef.Field
		if expanded.Kind == "object" {
			for _, f := range expanded.Fields {
				if f.Type.Kind == "literal" && !f.Optional {
					tags = append(tags, f)
				}
			}
			if len(tags) > 0 {
				label = ""
				for _, f := range tags {
					value := strings.Trim(f.Type.Literal, "\"")
					label += Name(value)
				}
			}
		}
		if used[label] {
			label += strconv.Itoa(i + 1)
		}
		used[label] = true
		expr, err := g.expr(m, name+label)
		if err != nil {
			return err
		}
		if err := g.reserve("New" + name + label); err != nil {
			return err
		}
		// A nullable member already has its own pointer representation.
		g.write("func New%s%s(value %s) (%s,error) {", name, label, expr, name)
		if expanded.Kind == "literal" {
			g.write("if value!=%s{return %s{},fmt.Errorf(%q)};", expanded.Literal, name, "invalid literal for "+name+"."+label)
		}
		if expanded.Kind == "null" {
			g.write("if len(value)!=0&&value.Kind()!='n'{return %s{},fmt.Errorf(%q)};", name, "expected null for "+name+"."+label)
		}

		if len(tags) > 0 && expanded.Kind == "object" {
			for _, f := range tags {
				g.write("value.%s = %s;", Name(f.Name), f.Type.Literal)
			}
		}
		g.write("b,err:=json.Marshal(value);if err!=nil{return %s{},err};return %s{raw:b},nil}\n", name, name)
		g.write("func (v %s) As%s() (value %s, ok bool) {", name, label, expr)
		if expanded.Kind == "null" {
			g.write("if v.raw.Kind()!='n'{return value,false};")
		}
		if !g.acceptsNull(expanded, map[string]bool{}) {
			g.write("if v.raw.Kind()=='n'||len(v.raw)==0{return value,false};")
		}
		if expanded.Kind == "object" {
			g.write("var fields map[string]jsontext.Value;if json.Unmarshal(v.raw,&fields)!=nil||fields==nil{return value,false};")
			for _, f := range expanded.Fields {
				if !f.Optional {
					g.write("if _,ok:=fields[%q];!ok{return value,false};", f.Name)
				}
			}
			for _, f := range expanded.Fields {
				if !g.acceptsNull(f.Type, map[string]bool{}) {
					g.write("if raw,ok:=fields[%q];ok&&raw.Kind()=='n'{return value,false};", f.Name)
				}
			}
		}

		if len(tags) > 0 {

			sort.Slice(tags, func(i, j int) bool { return tags[i].Name < tags[j].Name })
			for j, f := range tags {
				typ, _ := literals(f.Type)
				g.write("var tag%d %s;if json.Unmarshal(fields[%q],&tag%d)!=nil||tag%d!=%s{return value,false};", j, typ, f.Name, j, j, f.Type.Literal)
			}
		}
		if expanded.Kind == "literal" {
			g.write("decoded,ok:=decodeJSON[%s](v.raw);if !ok||decoded!=%s{return value,false};return decoded,true}\n", expr, expanded.Literal)
		} else {
			g.write("return decodeJSON[%s](v.raw)}\n", expr)
		}
	}
	return nil
}

// acceptsNull follows references without expanding recursive object fields.
func (g *generator) acceptsNull(t *tsdef.Type, seen map[string]bool) bool {
	switch t.Kind {
	case "null", "unknown", "any":
		return true
	case "ref":
		if seen[t.Name] {
			return false
		}
		seen[t.Name] = true
		defer delete(seen, t.Name)
		target := g.defs[t.Name]
		return target != nil && g.acceptsNull(target, seen)
	case "union":
		for _, m := range t.Members {
			if g.acceptsNull(m, seen) {
				return true
			}
		}
	case "intersection":
		for _, m := range t.Members {
			if !g.acceptsNull(m, seen) {
				return false
			}
		}
		return true
	}
	return false
}

func (g *generator) reserve(name string) error {
	if g.names[name] {
		return fmt.Errorf("duplicate Go declaration %s", name)
	}
	g.names[name] = true
	return nil
}
