// Code generated by acp-schema from the method table; DO NOT EDIT.

package acpv1

// The hand-written half of each façade provides AgentSideConnection and
// ClientSideConnection with a conn *jsonrpc.Connection field and an agent or
// client field holding the served interface; everything routed by method name
// is generated here.

import (
	"context"
	"encoding/json/jsontext"

	"github.com/ironpark/go-acp/internal/acpconn"
	"github.com/ironpark/go-acp/internal/jsonrpc"
	schema "github.com/ironpark/go-acp/schema/v1"
)

// Agent is the set of methods every ACP agent must handle.
//
// Everything beyond these four methods is optional and gated by a capability
// the agent advertises from [Agent.Initialize]. Implement the matching optional
// interface and the connection routes the method to it; when it is not
// implemented the peer receives "method not found".
//
// See protocol docs: [Agent](https://agentclientprotocol.com/protocol/overview#agent)
type Agent interface {
	// Initialize negotiates the protocol version and exchanges capabilities.
	//
	// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
	Initialize(ctx context.Context, params *InitializeRequest) (*InitializeResponse, error)

	// NewSession creates a conversation session with its own context.
	//
	// See protocol docs: [Session Setup](https://agentclientprotocol.com/protocol/session-setup)
	NewSession(ctx context.Context, params *NewSessionRequest) (*NewSessionResponse, error)

	// Prompt runs one prompt turn and returns once it stops.
	//
	// See protocol docs: [Prompt Turn](https://agentclientprotocol.com/protocol/prompt-turn)
	Prompt(ctx context.Context, params *PromptRequest) (*PromptResponse, error)

	// Cancel is a notification asking the agent to abort the current turn.
	// The pending Prompt call should return with StopReasonCancelled.
	//
	// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
	Cancel(ctx context.Context, params *CancelNotification) error
}

// Authenticator handles authenticate. Implement it when the agent lists
// `authMethods` in its Initialize response; an agent that needs no
// credentials leaves it out and the method answers "method not found".
//
// See protocol docs: [Authentication](https://agentclientprotocol.com/protocol/authentication)
type Authenticator interface {
	Authenticate(ctx context.Context, params *AuthenticateRequest) (*AuthenticateResponse, error)
}

// SessionLoader handles session/load. Advertise it with the `loadSession`
// agent capability. [SessionManager] provides an implementation.
type SessionLoader interface {
	LoadSession(ctx context.Context, params *LoadSessionRequest) (*LoadSessionResponse, error)
}

// SessionLister handles session/list. Advertise it with the
// `sessionCapabilities.list` agent capability.
type SessionLister interface {
	ListSessions(ctx context.Context, params *ListSessionsRequest) (*ListSessionsResponse, error)
}

// SessionDeleter handles session/delete. Advertise it with the
// `sessionCapabilities.delete` agent capability.
type SessionDeleter interface {
	DeleteSession(ctx context.Context, params *DeleteSessionRequest) (*DeleteSessionResponse, error)
}

// SessionForker handles session/fork. Advertise it with the
// `sessionCapabilities.fork` agent capability.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
type SessionForker interface {
	ForkSession(ctx context.Context, params *ForkSessionRequest) (*ForkSessionResponse, error)
}

// SessionResumer handles session/resume, continuing a session without
// replaying its history. Advertise it with the `sessionCapabilities.resume`
// agent capability.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
type SessionResumer interface {
	ResumeSession(ctx context.Context, params *ResumeSessionRequest) (*ResumeSessionResponse, error)
}

// SessionCloser handles session/close. Advertise it with the
// `sessionCapabilities.close` agent capability.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
type SessionCloser interface {
	CloseSession(ctx context.Context, params *CloseSessionRequest) (*CloseSessionResponse, error)
}

// SessionModeSetter handles session/set_mode.
//
// See protocol docs: [Session Modes](https://agentclientprotocol.com/protocol/session-modes)
type SessionModeSetter interface {
	SetSessionMode(ctx context.Context, params *SetSessionModeRequest) (*SetSessionModeResponse, error)
}

// SessionConfigOptionSetter handles session/set_config_option. The response
// carries every option and its current value, since changing one option may
// change the others.
type SessionConfigOptionSetter interface {
	SetSessionConfigOption(ctx context.Context, params *SetSessionConfigOptionRequest) (*SetSessionConfigOptionResponse, error)
}

// ProviderManager handles the providers/* methods. Advertise them with the
// `providers` agent capability.
//
// **UNSTABLE**: these methods are not part of the spec yet and may change.
type ProviderManager interface {
	ListProviders(ctx context.Context, params *ListProvidersRequest) (*ListProvidersResponse, error)

	SetProvider(ctx context.Context, params *SetProviderRequest) (*SetProviderResponse, error)

	DisableProvider(ctx context.Context, params *DisableProviderRequest) (*DisableProviderResponse, error)
}

// LogoutHandler handles the logout method, clearing stored credentials.
type LogoutHandler interface {
	Logout(ctx context.Context, params *LogoutRequest) (*LogoutResponse, error)
}

// NesHandler handles the nes/* methods for Next Edit Suggestions. Advertise
// them with the `nes` agent capability. AcceptNes and RejectNes are
// notifications.
//
// **UNSTABLE**: these methods are not part of the spec yet and may change.
type NesHandler interface {
	StartNes(ctx context.Context, params *StartNesRequest) (*StartNesResponse, error)

	SuggestNes(ctx context.Context, params *SuggestNesRequest) (*SuggestNesResponse, error)

	CloseNes(ctx context.Context, params *CloseNesRequest) (*CloseNesResponse, error)

	AcceptNes(ctx context.Context, params *AcceptNesNotification) error

	RejectNes(ctx context.Context, params *RejectNesNotification) error
}

// DocumentHandler receives the document/did* notifications that mirror the
// client's open editors.
//
// **UNSTABLE**: these notifications are not part of the spec yet and may change.
type DocumentHandler interface {
	DidOpenDocument(ctx context.Context, params *DidOpenDocumentNotification) error

	DidChangeDocument(ctx context.Context, params *DidChangeDocumentNotification) error

	DidCloseDocument(ctx context.Context, params *DidCloseDocumentNotification) error

	DidSaveDocument(ctx context.Context, params *DidSaveDocumentNotification) error

	DidFocusDocument(ctx context.Context, params *DidFocusDocumentNotification) error
}

// Client is the set of methods every ACP client must handle.
//
// File system, terminal and elicitation support are optional; implement the
// matching interface and advertise the capability from
// `InitializeRequest.ClientCapabilities`.
//
// See protocol docs: [Client](https://agentclientprotocol.com/protocol/overview#client)
type Client interface {
	// SessionUpdate is a notification streaming turn progress to the user.
	//
	// Notifications are handled one at a time on the connection's read loop, which
	// keeps updates in order and ahead of the prompt response. The flip side: a
	// handler that calls the agent and waits for the answer blocks the loop that
	// would read it. Hand such calls to a goroutine.
	//
	// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
	SessionUpdate(ctx context.Context, params *SessionNotification) error

	// RequestPermission asks the user to authorize a tool call.
	//
	// When the turn is cancelled the client MUST answer with the cancelled
	// outcome rather than leaving the request pending.
	//
	// See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/tool-calls#requesting-permission)
	RequestPermission(ctx context.Context, params *RequestPermissionRequest) (*RequestPermissionResponse, error)
}

// FileReader handles fs/read_text_file. Advertise it with the
// `fs.readTextFile` client capability.
type FileReader interface {
	ReadTextFile(ctx context.Context, params *ReadTextFileRequest) (*ReadTextFileResponse, error)
}

// FileWriter handles fs/write_text_file. Advertise it with the
// `fs.writeTextFile` client capability.
type FileWriter interface {
	WriteTextFile(ctx context.Context, params *WriteTextFileRequest) (*WriteTextFileResponse, error)
}

// TerminalHandler handles every terminal/* method. Advertise it with the
// `terminal` client capability, which covers all five methods at once.
//
// See protocol docs: [Terminals](https://agentclientprotocol.com/protocol/terminals)
type TerminalHandler interface {
	CreateTerminal(ctx context.Context, params *CreateTerminalRequest) (*CreateTerminalResponse, error)

	TerminalOutput(ctx context.Context, params *TerminalOutputRequest) (*TerminalOutputResponse, error)

	ReleaseTerminal(ctx context.Context, params *ReleaseTerminalRequest) (*ReleaseTerminalResponse, error)

	WaitForTerminalExit(ctx context.Context, params *WaitForTerminalExitRequest) (*WaitForTerminalExitResponse, error)

	KillTerminal(ctx context.Context, params *KillTerminalRequest) (*KillTerminalResponse, error)
}

// ElicitationHandler handles elicitation/create and the elicitation/complete
// notification. Advertise it with the `elicitation` client capability.
type ElicitationHandler interface {
	CreateElicitation(ctx context.Context, params *CreateElicitationRequest) (*CreateElicitationResponse, error)

	CompleteElicitation(ctx context.Context, params *CompleteElicitationNotification) error
}

// --- Outgoing calls from ClientSideConnection to the peer ---

// Initialize negotiates the protocol version and exchanges capabilities. It is
// the first call on every connection.
func (c *ClientSideConnection) Initialize(ctx context.Context, params *InitializeRequest) (*InitializeResponse, error) {
	return acpconn.Call[InitializeResponse](ctx, c.conn, schema.AgentMethodsInitialize, params)
}

// NewSession creates a session. It may fail with an auth-required error.
func (c *ClientSideConnection) NewSession(ctx context.Context, params *NewSessionRequest) (*NewSessionResponse, error) {
	return acpconn.Call[NewSessionResponse](ctx, c.conn, schema.AgentMethodsSessionNew, params)
}

// Prompt runs one prompt turn and returns once the agent stops.
//
// Cancelling ctx cancels the JSON-RPC request; to cancel the turn itself with
// the protocol's own semantics, send [ClientSideConnection.Cancel].
//
// See protocol docs: [Prompt Turn](https://agentclientprotocol.com/protocol/prompt-turn)
func (c *ClientSideConnection) Prompt(ctx context.Context, params *PromptRequest) (*PromptResponse, error) {
	return acpconn.Call[PromptResponse](ctx, c.conn, schema.AgentMethodsSessionPrompt, params)
}

// Cancel asks the agent to end the current turn. The pending Prompt call
// returns with the cancelled stop reason.
//
// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
func (c *ClientSideConnection) Cancel(ctx context.Context, params *CancelNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsSessionCancel, params)
}

// Authenticate authenticates with one of the methods the agent advertised.
func (c *ClientSideConnection) Authenticate(ctx context.Context, params *AuthenticateRequest) (*AuthenticateResponse, error) {
	return acpconn.Call[AuthenticateResponse](ctx, c.conn, schema.AgentMethodsAuthenticate, params)
}

// LoadSession resumes a session and replays its history as notifications.
// Requires the agent's `loadSession` capability.
func (c *ClientSideConnection) LoadSession(ctx context.Context, params *LoadSessionRequest) (*LoadSessionResponse, error) {
	return acpconn.Call[LoadSessionResponse](ctx, c.conn, schema.AgentMethodsSessionLoad, params)
}

// ListSessions lists sessions, optionally filtered and paginated.
func (c *ClientSideConnection) ListSessions(ctx context.Context, params *ListSessionsRequest) (*ListSessionsResponse, error) {
	return acpconn.Call[ListSessionsResponse](ctx, c.conn, schema.AgentMethodsSessionList, params)
}

// DeleteSession deletes a session and its stored history.
func (c *ClientSideConnection) DeleteSession(ctx context.Context, params *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return acpconn.Call[DeleteSessionResponse](ctx, c.conn, schema.AgentMethodsSessionDelete, params)
}

// ForkSession branches a session so work continues without touching the
// original history.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) ForkSession(ctx context.Context, params *ForkSessionRequest) (*ForkSessionResponse, error) {
	return acpconn.Call[ForkSessionResponse](ctx, c.conn, schema.AgentMethodsSessionFork, params)
}

// ResumeSession continues a session without replaying its history.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) ResumeSession(ctx context.Context, params *ResumeSessionRequest) (*ResumeSessionResponse, error) {
	return acpconn.Call[ResumeSessionResponse](ctx, c.conn, schema.AgentMethodsSessionResume, params)
}

// CloseSession cancels any ongoing work and frees the session's resources.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) CloseSession(ctx context.Context, params *CloseSessionRequest) (*CloseSessionResponse, error) {
	return acpconn.Call[CloseSessionResponse](ctx, c.conn, schema.AgentMethodsSessionClose, params)
}

// SetSessionMode switches the session between the agent's advertised modes.
func (c *ClientSideConnection) SetSessionMode(ctx context.Context, params *SetSessionModeRequest) (*SetSessionModeResponse, error) {
	return acpconn.Call[SetSessionModeResponse](ctx, c.conn, schema.AgentMethodsSessionSetMode, params)
}

// SetSessionConfigOption sets one configuration option. The response returns
// every option, since one change may affect the others.
func (c *ClientSideConnection) SetSessionConfigOption(ctx context.Context, params *SetSessionConfigOptionRequest) (*SetSessionConfigOptionResponse, error) {
	return acpconn.Call[SetSessionConfigOptionResponse](ctx, c.conn, schema.AgentMethodsSessionSetConfigOption, params)
}

// ListProviders lists the model providers the agent can use.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) ListProviders(ctx context.Context, params *ListProvidersRequest) (*ListProvidersResponse, error) {
	return acpconn.Call[ListProvidersResponse](ctx, c.conn, schema.AgentMethodsProvidersList, params)
}

// SetProvider configures one provider.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) SetProvider(ctx context.Context, params *SetProviderRequest) (*SetProviderResponse, error) {
	return acpconn.Call[SetProviderResponse](ctx, c.conn, schema.AgentMethodsProvidersSet, params)
}

// DisableProvider turns one provider off.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) DisableProvider(ctx context.Context, params *DisableProviderRequest) (*DisableProviderResponse, error) {
	return acpconn.Call[DisableProviderResponse](ctx, c.conn, schema.AgentMethodsProvidersDisable, params)
}

// Logout clears the credentials the agent holds.
func (c *ClientSideConnection) Logout(ctx context.Context, params *LogoutRequest) (*LogoutResponse, error) {
	return acpconn.Call[LogoutResponse](ctx, c.conn, schema.AgentMethodsLogout, params)
}

// StartNes starts a Next Edit Suggestions stream.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) StartNes(ctx context.Context, params *StartNesRequest) (*StartNesResponse, error) {
	return acpconn.Call[StartNesResponse](ctx, c.conn, schema.AgentMethodsNesStart, params)
}

// SuggestNes asks for the next edit suggestion.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) SuggestNes(ctx context.Context, params *SuggestNesRequest) (*SuggestNesResponse, error) {
	return acpconn.Call[SuggestNesResponse](ctx, c.conn, schema.AgentMethodsNesSuggest, params)
}

// CloseNes ends a Next Edit Suggestions stream.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) CloseNes(ctx context.Context, params *CloseNesRequest) (*CloseNesResponse, error) {
	return acpconn.Call[CloseNesResponse](ctx, c.conn, schema.AgentMethodsNesClose, params)
}

// AcceptNes reports that the user accepted a suggestion.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) AcceptNes(ctx context.Context, params *AcceptNesNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsNesAccept, params)
}

// RejectNes reports that the user rejected a suggestion.
//
// **UNSTABLE**: this capability is not part of the spec yet and may change.
func (c *ClientSideConnection) RejectNes(ctx context.Context, params *RejectNesNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsNesReject, params)
}

// DidOpenDocument tells the agent a document was opened.
//
// **UNSTABLE**: this notification is not part of the spec yet and may change.
func (c *ClientSideConnection) DidOpenDocument(ctx context.Context, params *DidOpenDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidOpen, params)
}

// DidChangeDocument tells the agent a document changed.
//
// **UNSTABLE**: this notification is not part of the spec yet and may change.
func (c *ClientSideConnection) DidChangeDocument(ctx context.Context, params *DidChangeDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidChange, params)
}

// DidCloseDocument tells the agent a document was closed.
//
// **UNSTABLE**: this notification is not part of the spec yet and may change.
func (c *ClientSideConnection) DidCloseDocument(ctx context.Context, params *DidCloseDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidClose, params)
}

// DidSaveDocument tells the agent a document was saved.
//
// **UNSTABLE**: this notification is not part of the spec yet and may change.
func (c *ClientSideConnection) DidSaveDocument(ctx context.Context, params *DidSaveDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidSave, params)
}

// DidFocusDocument tells the agent a document was focused.
//
// **UNSTABLE**: this notification is not part of the spec yet and may change.
func (c *ClientSideConnection) DidFocusDocument(ctx context.Context, params *DidFocusDocumentNotification) error {
	return c.conn.SendNotification(ctx, schema.AgentMethodsDocumentDidFocus, params)
}

// --- Outgoing calls from AgentSideConnection to the peer ---

// SessionUpdate streams turn progress to the client.
func (c *AgentSideConnection) SessionUpdate(ctx context.Context, params *SessionNotification) error {
	return c.conn.SendNotification(ctx, schema.ClientMethodsSessionUpdate, params)
}

// RequestPermission asks the user to authorize a tool call.
func (c *AgentSideConnection) RequestPermission(ctx context.Context, params *RequestPermissionRequest) (*RequestPermissionResponse, error) {
	return acpconn.Call[RequestPermissionResponse](ctx, c.conn, schema.ClientMethodsSessionRequestPermission, params)
}

// ReadTextFile reads a text file through the client. Requires the client's
// `fs.readTextFile` capability.
func (c *AgentSideConnection) ReadTextFile(ctx context.Context, params *ReadTextFileRequest) (*ReadTextFileResponse, error) {
	return acpconn.Call[ReadTextFileResponse](ctx, c.conn, schema.ClientMethodsFsReadTextFile, params)
}

// WriteTextFile writes a text file through the client. Requires the client's
// `fs.writeTextFile` capability.
func (c *AgentSideConnection) WriteTextFile(ctx context.Context, params *WriteTextFileRequest) (*WriteTextFileResponse, error) {
	return acpconn.Call[WriteTextFileResponse](ctx, c.conn, schema.ClientMethodsFsWriteTextFile, params)
}

// CreateTerminal starts a command in a client-managed terminal. Requires the
// client's `terminal` capability. [AgentSideConnection.NewTerminal] also returns
// a handle bound to the new terminal.
func (c *AgentSideConnection) CreateTerminal(ctx context.Context, params *CreateTerminalRequest) (*CreateTerminalResponse, error) {
	return acpconn.Call[CreateTerminalResponse](ctx, c.conn, schema.ClientMethodsTerminalCreate, params)
}

// TerminalOutput returns a terminal's output so far without waiting for exit.
func (c *AgentSideConnection) TerminalOutput(ctx context.Context, params *TerminalOutputRequest) (*TerminalOutputResponse, error) {
	return acpconn.Call[TerminalOutputResponse](ctx, c.conn, schema.ClientMethodsTerminalOutput, params)
}

// ReleaseTerminal kills the command if needed and frees the terminal.
func (c *AgentSideConnection) ReleaseTerminal(ctx context.Context, params *ReleaseTerminalRequest) (*ReleaseTerminalResponse, error) {
	return acpconn.Call[ReleaseTerminalResponse](ctx, c.conn, schema.ClientMethodsTerminalRelease, params)
}

// WaitForTerminalExit blocks until the terminal's command exits.
func (c *AgentSideConnection) WaitForTerminalExit(ctx context.Context, params *WaitForTerminalExitRequest) (*WaitForTerminalExitResponse, error) {
	return acpconn.Call[WaitForTerminalExitResponse](ctx, c.conn, schema.ClientMethodsTerminalWaitForExit, params)
}

// KillTerminal kills the command but keeps the terminal id valid.
func (c *AgentSideConnection) KillTerminal(ctx context.Context, params *KillTerminalRequest) (*KillTerminalResponse, error) {
	return acpconn.Call[KillTerminalResponse](ctx, c.conn, schema.ClientMethodsTerminalKill, params)
}

// CreateElicitation asks the client to collect input from the user. Requires
// the client's `elicitation` capability.
func (c *AgentSideConnection) CreateElicitation(ctx context.Context, params *CreateElicitationRequest) (*CreateElicitationResponse, error) {
	return acpconn.Call[CreateElicitationResponse](ctx, c.conn, schema.ClientMethodsElicitationCreate, params)
}

// CompleteElicitation tells the client an elicitation no longer needs an answer.
func (c *AgentSideConnection) CompleteElicitation(ctx context.Context, params *CompleteElicitationNotification) error {
	return c.conn.SendNotification(ctx, schema.ClientMethodsElicitationComplete, params)
}

func (c *AgentSideConnection) handleRequest(ctx context.Context, method string, params jsontext.Value) (any, error) {
	switch method {
	case schema.AgentMethodsInitialize:
		return acpconn.Request(ctx, schema.Validated, params, c.agent.Initialize)
	case schema.AgentMethodsSessionNew:
		return acpconn.Request(ctx, schema.Validated, params, c.agent.NewSession)
	case schema.AgentMethodsSessionPrompt:
		return acpconn.Request(ctx, schema.Validated, params, c.agent.Prompt)
	case schema.AgentMethodsAuthenticate:
		if h, ok := c.agent.(Authenticator); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.Authenticate)
		}
	case schema.AgentMethodsSessionLoad:
		if h, ok := c.agent.(SessionLoader); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.LoadSession)
		}
	case schema.AgentMethodsSessionList:
		if h, ok := c.agent.(SessionLister); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.ListSessions)
		}
	case schema.AgentMethodsSessionDelete:
		if h, ok := c.agent.(SessionDeleter); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.DeleteSession)
		}
	case schema.AgentMethodsSessionFork:
		if h, ok := c.agent.(SessionForker); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.ForkSession)
		}
	case schema.AgentMethodsSessionResume:
		if h, ok := c.agent.(SessionResumer); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.ResumeSession)
		}
	case schema.AgentMethodsSessionClose:
		if h, ok := c.agent.(SessionCloser); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.CloseSession)
		}
	case schema.AgentMethodsSessionSetMode:
		if h, ok := c.agent.(SessionModeSetter); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.SetSessionMode)
		}
	case schema.AgentMethodsSessionSetConfigOption:
		if h, ok := c.agent.(SessionConfigOptionSetter); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.SetSessionConfigOption)
		}
	case schema.AgentMethodsProvidersList:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.ListProviders)
		}
	case schema.AgentMethodsProvidersSet:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.SetProvider)
		}
	case schema.AgentMethodsProvidersDisable:
		if h, ok := c.agent.(ProviderManager); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.DisableProvider)
		}
	case schema.AgentMethodsLogout:
		if h, ok := c.agent.(LogoutHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.Logout)
		}
	case schema.AgentMethodsNesStart:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.StartNes)
		}
	case schema.AgentMethodsNesSuggest:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.SuggestNes)
		}
	case schema.AgentMethodsNesClose:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.CloseNes)
		}
	default:
		if h, ok := c.agent.(ExtMethodHandler); ok {
			return h.ExtMethod(ctx, method, params)
		}
	}
	return nil, jsonrpc.MethodNotFound(method)
}

func (c *AgentSideConnection) handleNotification(ctx context.Context, method string, params jsontext.Value) error {
	switch method {
	case schema.AgentMethodsSessionCancel:
		return acpconn.Notify(ctx, schema.Validated, params, c.agent.Cancel)
	case schema.AgentMethodsNesAccept:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Notify(ctx, schema.Validated, params, h.AcceptNes)
		}
	case schema.AgentMethodsNesReject:
		if h, ok := c.agent.(NesHandler); ok {
			return acpconn.Notify(ctx, schema.Validated, params, h.RejectNes)
		}
	case schema.AgentMethodsDocumentDidOpen:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated, params, h.DidOpenDocument)
		}
	case schema.AgentMethodsDocumentDidChange:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated, params, h.DidChangeDocument)
		}
	case schema.AgentMethodsDocumentDidClose:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated, params, h.DidCloseDocument)
		}
	case schema.AgentMethodsDocumentDidSave:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated, params, h.DidSaveDocument)
		}
	case schema.AgentMethodsDocumentDidFocus:
		if h, ok := c.agent.(DocumentHandler); ok {
			return acpconn.Notify(ctx, schema.Validated, params, h.DidFocusDocument)
		}
	default:
		if h, ok := c.agent.(ExtNotificationHandler); ok {
			return h.ExtNotification(ctx, method, params)
		}
	}
	return jsonrpc.MethodNotFound(method)
}

func (c *ClientSideConnection) handleRequest(ctx context.Context, method string, params jsontext.Value) (any, error) {
	switch method {
	case schema.ClientMethodsSessionRequestPermission:
		return acpconn.Request(ctx, schema.Validated, params, c.client.RequestPermission)
	case schema.ClientMethodsFsReadTextFile:
		if h, ok := c.client.(FileReader); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.ReadTextFile)
		}
	case schema.ClientMethodsFsWriteTextFile:
		if h, ok := c.client.(FileWriter); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.WriteTextFile)
		}
	case schema.ClientMethodsTerminalCreate:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.CreateTerminal)
		}
	case schema.ClientMethodsTerminalOutput:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.TerminalOutput)
		}
	case schema.ClientMethodsTerminalRelease:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.ReleaseTerminal)
		}
	case schema.ClientMethodsTerminalWaitForExit:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.WaitForTerminalExit)
		}
	case schema.ClientMethodsTerminalKill:
		if h, ok := c.client.(TerminalHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.KillTerminal)
		}
	case schema.ClientMethodsElicitationCreate:
		if h, ok := c.client.(ElicitationHandler); ok {
			return acpconn.Request(ctx, schema.Validated, params, h.CreateElicitation)
		}
	default:
		if h, ok := c.client.(ExtMethodHandler); ok {
			return h.ExtMethod(ctx, method, params)
		}
	}
	return nil, jsonrpc.MethodNotFound(method)
}

func (c *ClientSideConnection) handleNotification(ctx context.Context, method string, params jsontext.Value) error {
	switch method {
	case schema.ClientMethodsSessionUpdate:
		return acpconn.Notify(ctx, schema.Validated, params, c.sessionUpdate)
	case schema.ClientMethodsElicitationComplete:
		if h, ok := c.client.(ElicitationHandler); ok {
			return acpconn.Notify(ctx, schema.Validated, params, h.CompleteElicitation)
		}
	default:
		if h, ok := c.client.(ExtNotificationHandler); ok {
			return h.ExtNotification(ctx, method, params)
		}
	}
	return jsonrpc.MethodNotFound(method)
}
