// Code generated by acp-schema from the TypeScript SDK; DO NOT EDIT.

package schema

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"reflect"
)

var _ = json.Marshal
var _ = fmt.Errorf
var _ jsontext.Value
var _ = reflect.TypeFor[int]

// A JSON-RPC request object.
type AgentRequest struct {
	// The request id used to correlate the matching response.
	ID RequestID `json:"id"`
	// The method name to invoke.
	Method string `json:"method"`
	// Method-specific request parameters.
	Params AgentRequestParams `json:"params,omitzero"`
}

// JSON RPC Request Id
//
// An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null \[1\] and Numbers SHOULD NOT contain fractional parts \[2\]
//
// The Server MUST reply with the same value in the Response object if included. This member is used to correlate the context between the two objects.
//
// \[1\] The use of Null as a value for the id member in a Request object is discouraged, because this specification uses a value of Null for Responses with an unknown id. Also, because JSON-RPC 1.0 uses an id value of Null for Notifications this could cause confusion in handling.
//
// \[2\] Fractional parts may be problematic, since many decimal fractions cannot be represented exactly as binary fractions.
// RequestID preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewRequestID to build one.
type RequestID struct{ raw jsontext.Value }

// RequestIDAlternative is the set of Go types a RequestID can hold.
type RequestIDAlternative interface {
	jsontext.Value | float64 | string
}

var requestIDAlternatives = altRules{
	reflect.TypeFor[jsontext.Value](): {{null: true}},
	reflect.TypeFor[float64]():        {{nonNull: true}},
	reflect.TypeFor[string]():         {{nonNull: true}},
}

// NewRequestID encodes value as a RequestID, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewRequestID[T RequestIDAlternative](value T) (RequestID, error) {
	raw, err := newAlternative("RequestID", requestIDAlternatives, value)
	return RequestID{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v RequestID) As[T RequestIDAlternative]() (T, error) {
	return asAlternative[T]("RequestID", requestIDAlternatives, v.raw)
}
func (v RequestID) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *RequestID) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid RequestID JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v RequestID) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v RequestID) IsZero() bool { return len(v.raw) == 0 }
func (v RequestID) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *RequestID) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseRequestID(b []byte) (RequestID, error) {
	var v RequestID
	err := json.Unmarshal(b, &v)
	return v, err
}

// A JSON-RPC response object.
// AgentResponse preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewAgentResponse to build one.
type AgentResponse struct{ raw jsontext.Value }

// AgentResponseAlternative is the set of Go types a AgentResponse can hold.
type AgentResponseAlternative interface {
	AgentResponseResult | AgentResponseError
}

var agentResponseAlternatives = altRules{
	reflect.TypeFor[AgentResponseResult](): {{nonNull: true, required: []string{"id", "result"}}},
	reflect.TypeFor[AgentResponseError]():  {{nonNull: true, required: []string{"id", "error"}, notNull: []string{"error"}}},
}

// NewAgentResponse encodes value as a AgentResponse, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewAgentResponse[T AgentResponseAlternative](value T) (AgentResponse, error) {
	raw, err := newAlternative("AgentResponse", agentResponseAlternatives, value)
	return AgentResponse{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v AgentResponse) As[T AgentResponseAlternative]() (T, error) {
	return asAlternative[T]("AgentResponse", agentResponseAlternatives, v.raw)
}
func (v AgentResponse) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *AgentResponse) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid AgentResponse JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v AgentResponse) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v AgentResponse) IsZero() bool { return len(v.raw) == 0 }
func (v AgentResponse) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *AgentResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseAgentResponse(b []byte) (AgentResponse, error) {
	var v AgentResponse
	err := json.Unmarshal(b, &v)
	return v, err
}

// JSON-RPC error object.
//
// Represents an error that occurred during method execution, following the
// JSON-RPC 2.0 error object specification with optional additional data.
//
// See protocol docs: [JSON-RPC Error Object](https://www.jsonrpc.org/specification#error_object)
type Error struct {
	// A number indicating the error type that occurred.
	// This must be an integer as defined in the JSON-RPC specification.
	Code ErrorCode `json:"code"`
	// A string providing a short description of the error.
	// The message should be limited to a concise single sentence.
	Message string `json:"message"`
	// Optional primitive or structured value that contains additional information about the error.
	// This may include debugging information or context-specific details.
	Data jsontext.Value `json:"data,omitzero"`
}

// A JSON-RPC notification object.
type AgentNotification struct {
	// The notification method name.
	Method string `json:"method"`
	// Method-specific notification parameters.
	Params AgentNotificationParams `json:"params,omitzero"`
}

// A JSON-RPC request object.
type ClientRequest struct {
	// The request id used to correlate the matching response.
	ID RequestID `json:"id"`
	// The method name to invoke.
	Method string `json:"method"`
	// Method-specific request parameters.
	Params ClientRequestParams `json:"params,omitzero"`
}

// A JSON-RPC response object.
// ClientResponse preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewClientResponse to build one.
type ClientResponse struct{ raw jsontext.Value }

// ClientResponseAlternative is the set of Go types a ClientResponse can hold.
type ClientResponseAlternative interface {
	ClientResponseResult | ClientResponseError
}

var clientResponseAlternatives = altRules{
	reflect.TypeFor[ClientResponseResult](): {{nonNull: true, required: []string{"id", "result"}}},
	reflect.TypeFor[ClientResponseError]():  {{nonNull: true, required: []string{"id", "error"}, notNull: []string{"error"}}},
}

// NewClientResponse encodes value as a ClientResponse, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewClientResponse[T ClientResponseAlternative](value T) (ClientResponse, error) {
	raw, err := newAlternative("ClientResponse", clientResponseAlternatives, value)
	return ClientResponse{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v ClientResponse) As[T ClientResponseAlternative]() (T, error) {
	return asAlternative[T]("ClientResponse", clientResponseAlternatives, v.raw)
}
func (v ClientResponse) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *ClientResponse) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid ClientResponse JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v ClientResponse) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v ClientResponse) IsZero() bool { return len(v.raw) == 0 }
func (v ClientResponse) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *ClientResponse) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseClientResponse(b []byte) (ClientResponse, error) {
	var v ClientResponse
	err := json.Unmarshal(b, &v)
	return v, err
}

// A JSON-RPC notification object.
type ClientNotification struct {
	// The notification method name.
	Method string `json:"method"`
	// Method-specific notification parameters.
	Params ClientNotificationParams `json:"params,omitzero"`
}

// AgentRequestParams preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewAgentRequestParams to build one.
type AgentRequestParams struct{ raw jsontext.Value }

// AgentRequestParamsAlternative is the set of Go types a AgentRequestParams can hold.
type AgentRequestParamsAlternative interface {
	WriteTextFileRequest | ReadTextFileRequest | RequestPermissionRequest | CreateTerminalRequest | TerminalOutputRequest | ReleaseTerminalRequest | WaitForTerminalExitRequest | KillTerminalRequest | CreateElicitationRequest | ConnectMCPRequest | MessageMCPRequest | DisconnectMCPRequest | jsontext.Value
}

var agentRequestParamsAlternatives = altRules{
	reflect.TypeFor[WriteTextFileRequest]():       {{nonNull: true, required: []string{"sessionId", "path", "content"}, notNull: []string{"sessionId", "path", "content"}}},
	reflect.TypeFor[ReadTextFileRequest]():        {{nonNull: true, required: []string{"sessionId", "path"}, notNull: []string{"sessionId", "path"}}},
	reflect.TypeFor[RequestPermissionRequest]():   {{nonNull: true, required: []string{"sessionId", "toolCall", "options"}, notNull: []string{"sessionId", "toolCall", "options"}}},
	reflect.TypeFor[CreateTerminalRequest]():      {{nonNull: true, required: []string{"sessionId", "command"}, notNull: []string{"sessionId", "command", "args", "env"}}},
	reflect.TypeFor[TerminalOutputRequest]():      {{nonNull: true, required: []string{"sessionId", "terminalId"}, notNull: []string{"sessionId", "terminalId"}}},
	reflect.TypeFor[ReleaseTerminalRequest]():     {{nonNull: true, required: []string{"sessionId", "terminalId"}, notNull: []string{"sessionId", "terminalId"}}},
	reflect.TypeFor[WaitForTerminalExitRequest](): {{nonNull: true, required: []string{"sessionId", "terminalId"}, notNull: []string{"sessionId", "terminalId"}}},
	reflect.TypeFor[KillTerminalRequest]():        {{nonNull: true, required: []string{"sessionId", "terminalId"}, notNull: []string{"sessionId", "terminalId"}}},
	reflect.TypeFor[CreateElicitationRequest]():   {{nonNull: true}},
	reflect.TypeFor[ConnectMCPRequest]():          {{nonNull: true, required: []string{"serverId"}, notNull: []string{"serverId"}}},
	reflect.TypeFor[MessageMCPRequest]():          {{nonNull: true, required: []string{"connectionId", "method"}, notNull: []string{"connectionId", "method"}}},
	reflect.TypeFor[DisconnectMCPRequest]():       {{nonNull: true, required: []string{"connectionId"}, notNull: []string{"connectionId"}}},
	reflect.TypeFor[jsontext.Value]():             {{}},
}

// NewAgentRequestParams encodes value as a AgentRequestParams, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewAgentRequestParams[T AgentRequestParamsAlternative](value T) (AgentRequestParams, error) {
	raw, err := newAlternative("AgentRequestParams", agentRequestParamsAlternatives, value)
	return AgentRequestParams{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v AgentRequestParams) As[T AgentRequestParamsAlternative]() (T, error) {
	return asAlternative[T]("AgentRequestParams", agentRequestParamsAlternatives, v.raw)
}
func (v AgentRequestParams) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *AgentRequestParams) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid AgentRequestParams JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v AgentRequestParams) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v AgentRequestParams) IsZero() bool { return len(v.raw) == 0 }
func (v AgentRequestParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *AgentRequestParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseAgentRequestParams(b []byte) (AgentRequestParams, error) {
	var v AgentRequestParams
	err := json.Unmarshal(b, &v)
	return v, err
}

type AgentResponseResult struct {
	// The id of the request this response answers.
	ID RequestID `json:"id"`
	// Method-specific response data.
	Result AgentResponseResultResult `json:"result"`
}

type AgentResponseError struct {
	// The id of the request this response answers.
	ID RequestID `json:"id"`
	// Method-specific error data.
	Error Error `json:"error"`
}

// AgentNotificationParams preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewAgentNotificationParams to build one.
type AgentNotificationParams struct{ raw jsontext.Value }

// AgentNotificationParamsAlternative is the set of Go types a AgentNotificationParams can hold.
type AgentNotificationParamsAlternative interface {
	SessionNotification | CompleteElicitationNotification | MessageMCPNotification | jsontext.Value
}

var agentNotificationParamsAlternatives = altRules{
	reflect.TypeFor[SessionNotification]():             {{nonNull: true, required: []string{"sessionId", "update"}, notNull: []string{"sessionId", "update"}}},
	reflect.TypeFor[CompleteElicitationNotification](): {{nonNull: true, required: []string{"elicitationId"}, notNull: []string{"elicitationId"}}},
	reflect.TypeFor[MessageMCPNotification]():          {{nonNull: true, required: []string{"connectionId", "method"}, notNull: []string{"connectionId", "method"}}},
	reflect.TypeFor[jsontext.Value]():                  {{}},
}

// NewAgentNotificationParams encodes value as a AgentNotificationParams, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewAgentNotificationParams[T AgentNotificationParamsAlternative](value T) (AgentNotificationParams, error) {
	raw, err := newAlternative("AgentNotificationParams", agentNotificationParamsAlternatives, value)
	return AgentNotificationParams{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v AgentNotificationParams) As[T AgentNotificationParamsAlternative]() (T, error) {
	return asAlternative[T]("AgentNotificationParams", agentNotificationParamsAlternatives, v.raw)
}
func (v AgentNotificationParams) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *AgentNotificationParams) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid AgentNotificationParams JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v AgentNotificationParams) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v AgentNotificationParams) IsZero() bool { return len(v.raw) == 0 }
func (v AgentNotificationParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *AgentNotificationParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseAgentNotificationParams(b []byte) (AgentNotificationParams, error) {
	var v AgentNotificationParams
	err := json.Unmarshal(b, &v)
	return v, err
}

// ClientRequestParams preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewClientRequestParams to build one.
type ClientRequestParams struct{ raw jsontext.Value }

// ClientRequestParamsAlternative is the set of Go types a ClientRequestParams can hold.
type ClientRequestParamsAlternative interface {
	InitializeRequest | AuthenticateRequest | ListProvidersRequest | SetProviderRequest | DisableProviderRequest | LogoutRequest | NewSessionRequest | LoadSessionRequest | ListSessionsRequest | DeleteSessionRequest | ForkSessionRequest | ResumeSessionRequest | CloseSessionRequest | SetSessionModeRequest | SetSessionConfigOptionRequest | PromptRequest | StartNesRequest | SuggestNesRequest | CloseNesRequest | MessageMCPRequest | jsontext.Value
}

var clientRequestParamsAlternatives = altRules{
	reflect.TypeFor[InitializeRequest]():             {{nonNull: true, required: []string{"protocolVersion"}, notNull: []string{"protocolVersion", "clientCapabilities"}}},
	reflect.TypeFor[AuthenticateRequest]():           {{nonNull: true, required: []string{"methodId"}, notNull: []string{"methodId"}}},
	reflect.TypeFor[ListProvidersRequest]():          {{nonNull: true}},
	reflect.TypeFor[SetProviderRequest]():            {{nonNull: true, required: []string{"providerId", "apiType", "baseUrl"}, notNull: []string{"providerId", "apiType", "baseUrl", "headers"}}},
	reflect.TypeFor[DisableProviderRequest]():        {{nonNull: true, required: []string{"providerId"}, notNull: []string{"providerId"}}},
	reflect.TypeFor[LogoutRequest]():                 {{nonNull: true}},
	reflect.TypeFor[NewSessionRequest]():             {{nonNull: true, required: []string{"cwd", "mcpServers"}, notNull: []string{"cwd", "additionalDirectories", "mcpServers"}}},
	reflect.TypeFor[LoadSessionRequest]():            {{nonNull: true, required: []string{"mcpServers", "cwd", "sessionId"}, notNull: []string{"mcpServers", "cwd", "additionalDirectories", "sessionId"}}},
	reflect.TypeFor[ListSessionsRequest]():           {{nonNull: true}},
	reflect.TypeFor[DeleteSessionRequest]():          {{nonNull: true, required: []string{"sessionId"}, notNull: []string{"sessionId"}}},
	reflect.TypeFor[ForkSessionRequest]():            {{nonNull: true, required: []string{"sessionId", "cwd"}, notNull: []string{"sessionId", "cwd", "additionalDirectories", "mcpServers"}}},
	reflect.TypeFor[ResumeSessionRequest]():          {{nonNull: true, required: []string{"sessionId", "cwd"}, notNull: []string{"sessionId", "cwd", "additionalDirectories", "mcpServers"}}},
	reflect.TypeFor[CloseSessionRequest]():           {{nonNull: true, required: []string{"sessionId"}, notNull: []string{"sessionId"}}},
	reflect.TypeFor[SetSessionModeRequest]():         {{nonNull: true, required: []string{"sessionId", "modeId"}, notNull: []string{"sessionId", "modeId"}}},
	reflect.TypeFor[SetSessionConfigOptionRequest](): {{nonNull: true}},
	reflect.TypeFor[PromptRequest]():                 {{nonNull: true, required: []string{"sessionId", "prompt"}, notNull: []string{"sessionId", "prompt"}}},
	reflect.TypeFor[StartNesRequest]():               {{nonNull: true}},
	reflect.TypeFor[SuggestNesRequest]():             {{nonNull: true, required: []string{"sessionId", "uri", "version", "position", "triggerKind"}, notNull: []string{"sessionId", "uri", "version", "position", "triggerKind"}}},
	reflect.TypeFor[CloseNesRequest]():               {{nonNull: true, required: []string{"sessionId"}, notNull: []string{"sessionId"}}},
	reflect.TypeFor[MessageMCPRequest]():             {{nonNull: true, required: []string{"connectionId", "method"}, notNull: []string{"connectionId", "method"}}},
	reflect.TypeFor[jsontext.Value]():                {{}},
}

// NewClientRequestParams encodes value as a ClientRequestParams, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewClientRequestParams[T ClientRequestParamsAlternative](value T) (ClientRequestParams, error) {
	raw, err := newAlternative("ClientRequestParams", clientRequestParamsAlternatives, value)
	return ClientRequestParams{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v ClientRequestParams) As[T ClientRequestParamsAlternative]() (T, error) {
	return asAlternative[T]("ClientRequestParams", clientRequestParamsAlternatives, v.raw)
}
func (v ClientRequestParams) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *ClientRequestParams) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid ClientRequestParams JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v ClientRequestParams) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v ClientRequestParams) IsZero() bool { return len(v.raw) == 0 }
func (v ClientRequestParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *ClientRequestParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseClientRequestParams(b []byte) (ClientRequestParams, error) {
	var v ClientRequestParams
	err := json.Unmarshal(b, &v)
	return v, err
}

type ClientResponseResult struct {
	// The id of the request this response answers.
	ID RequestID `json:"id"`
	// Method-specific response data.
	Result ClientResponseResultResult `json:"result"`
}

type ClientResponseError struct {
	// The id of the request this response answers.
	ID RequestID `json:"id"`
	// Method-specific error data.
	Error Error `json:"error"`
}

// ClientNotificationParams preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewClientNotificationParams to build one.
type ClientNotificationParams struct{ raw jsontext.Value }

// ClientNotificationParamsAlternative is the set of Go types a ClientNotificationParams can hold.
type ClientNotificationParamsAlternative interface {
	CancelNotification | DidOpenDocumentNotification | DidChangeDocumentNotification | DidCloseDocumentNotification | DidSaveDocumentNotification | DidFocusDocumentNotification | AcceptNesNotification | RejectNesNotification | MessageMCPNotification | jsontext.Value
}

var clientNotificationParamsAlternatives = altRules{
	reflect.TypeFor[CancelNotification]():            {{nonNull: true, required: []string{"sessionId"}, notNull: []string{"sessionId"}}},
	reflect.TypeFor[DidOpenDocumentNotification]():   {{nonNull: true, required: []string{"sessionId", "uri", "languageId", "version", "text"}, notNull: []string{"sessionId", "uri", "languageId", "version", "text"}}},
	reflect.TypeFor[DidChangeDocumentNotification](): {{nonNull: true, required: []string{"sessionId", "uri", "version", "contentChanges"}, notNull: []string{"sessionId", "uri", "version", "contentChanges"}}},
	reflect.TypeFor[DidCloseDocumentNotification]():  {{nonNull: true, required: []string{"sessionId", "uri"}, notNull: []string{"sessionId", "uri"}}},
	reflect.TypeFor[DidSaveDocumentNotification]():   {{nonNull: true, required: []string{"sessionId", "uri"}, notNull: []string{"sessionId", "uri"}}},
	reflect.TypeFor[DidFocusDocumentNotification]():  {{nonNull: true, required: []string{"sessionId", "uri", "version", "position", "visibleRange"}, notNull: []string{"sessionId", "uri", "version", "position", "visibleRange"}}},
	reflect.TypeFor[AcceptNesNotification]():         {{nonNull: true, required: []string{"sessionId", "id"}, notNull: []string{"sessionId", "id"}}},
	reflect.TypeFor[RejectNesNotification]():         {{nonNull: true, required: []string{"sessionId", "id"}, notNull: []string{"sessionId", "id"}}},
	reflect.TypeFor[MessageMCPNotification]():        {{nonNull: true, required: []string{"connectionId", "method"}, notNull: []string{"connectionId", "method"}}},
	reflect.TypeFor[jsontext.Value]():                {{}},
}

// NewClientNotificationParams encodes value as a ClientNotificationParams, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewClientNotificationParams[T ClientNotificationParamsAlternative](value T) (ClientNotificationParams, error) {
	raw, err := newAlternative("ClientNotificationParams", clientNotificationParamsAlternatives, value)
	return ClientNotificationParams{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v ClientNotificationParams) As[T ClientNotificationParamsAlternative]() (T, error) {
	return asAlternative[T]("ClientNotificationParams", clientNotificationParamsAlternatives, v.raw)
}
func (v ClientNotificationParams) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *ClientNotificationParams) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid ClientNotificationParams JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v ClientNotificationParams) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v ClientNotificationParams) IsZero() bool { return len(v.raw) == 0 }
func (v ClientNotificationParams) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *ClientNotificationParams) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseClientNotificationParams(b []byte) (ClientNotificationParams, error) {
	var v ClientNotificationParams
	err := json.Unmarshal(b, &v)
	return v, err
}

// AgentResponseResultResult preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewAgentResponseResultResult to build one.
type AgentResponseResultResult struct{ raw jsontext.Value }

// AgentResponseResultResultAlternative is the set of Go types a AgentResponseResultResult can hold.
type AgentResponseResultResultAlternative interface {
	InitializeResponse | AuthenticateResponse | ListProvidersResponse | SetProviderResponse | DisableProviderResponse | LogoutResponse | NewSessionResponse | LoadSessionResponse | ListSessionsResponse | DeleteSessionResponse | ForkSessionResponse | ResumeSessionResponse | CloseSessionResponse | SetSessionModeResponse | SetSessionConfigOptionResponse | PromptResponse | StartNesResponse | SuggestNesResponse | CloseNesResponse | jsontext.Value
}

var agentResponseResultResultAlternatives = altRules{
	reflect.TypeFor[InitializeResponse]():             {{nonNull: true, required: []string{"protocolVersion"}, notNull: []string{"protocolVersion", "agentCapabilities", "authMethods"}}},
	reflect.TypeFor[AuthenticateResponse]():           {{nonNull: true}},
	reflect.TypeFor[ListProvidersResponse]():          {{nonNull: true, required: []string{"providers"}, notNull: []string{"providers"}}},
	reflect.TypeFor[SetProviderResponse]():            {{nonNull: true}},
	reflect.TypeFor[DisableProviderResponse]():        {{nonNull: true}},
	reflect.TypeFor[LogoutResponse]():                 {{nonNull: true}},
	reflect.TypeFor[NewSessionResponse]():             {{nonNull: true, required: []string{"sessionId"}, notNull: []string{"sessionId"}}},
	reflect.TypeFor[LoadSessionResponse]():            {{nonNull: true}},
	reflect.TypeFor[ListSessionsResponse]():           {{nonNull: true, required: []string{"sessions"}, notNull: []string{"sessions"}}},
	reflect.TypeFor[DeleteSessionResponse]():          {{nonNull: true}},
	reflect.TypeFor[ForkSessionResponse]():            {{nonNull: true, required: []string{"sessionId"}, notNull: []string{"sessionId"}}},
	reflect.TypeFor[ResumeSessionResponse]():          {{nonNull: true}},
	reflect.TypeFor[CloseSessionResponse]():           {{nonNull: true}},
	reflect.TypeFor[SetSessionModeResponse]():         {{nonNull: true}},
	reflect.TypeFor[SetSessionConfigOptionResponse](): {{nonNull: true, required: []string{"configOptions"}, notNull: []string{"configOptions"}}},
	reflect.TypeFor[PromptResponse]():                 {{nonNull: true, required: []string{"stopReason"}, notNull: []string{"stopReason"}}},
	reflect.TypeFor[StartNesResponse]():               {{nonNull: true, required: []string{"sessionId"}, notNull: []string{"sessionId"}}},
	reflect.TypeFor[SuggestNesResponse]():             {{nonNull: true, required: []string{"suggestions"}, notNull: []string{"suggestions"}}},
	reflect.TypeFor[CloseNesResponse]():               {{nonNull: true}},
	reflect.TypeFor[jsontext.Value]():                 {{}, {}},
}

// NewAgentResponseResultResult encodes value as a AgentResponseResultResult, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewAgentResponseResultResult[T AgentResponseResultResultAlternative](value T) (AgentResponseResultResult, error) {
	raw, err := newAlternative("AgentResponseResultResult", agentResponseResultResultAlternatives, value)
	return AgentResponseResultResult{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v AgentResponseResultResult) As[T AgentResponseResultResultAlternative]() (T, error) {
	return asAlternative[T]("AgentResponseResultResult", agentResponseResultResultAlternatives, v.raw)
}
func (v AgentResponseResultResult) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *AgentResponseResultResult) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid AgentResponseResultResult JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v AgentResponseResultResult) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v AgentResponseResultResult) IsZero() bool { return len(v.raw) == 0 }
func (v AgentResponseResultResult) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *AgentResponseResultResult) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseAgentResponseResultResult(b []byte) (AgentResponseResultResult, error) {
	var v AgentResponseResultResult
	err := json.Unmarshal(b, &v)
	return v, err
}

// ClientResponseResultResult preserves the complete JSON payload, including future variants.
// Use As to read one alternative and NewClientResponseResultResult to build one.
type ClientResponseResultResult struct{ raw jsontext.Value }

// ClientResponseResultResultAlternative is the set of Go types a ClientResponseResultResult can hold.
type ClientResponseResultResultAlternative interface {
	WriteTextFileResponse | ReadTextFileResponse | RequestPermissionResponse | CreateTerminalResponse | TerminalOutputResponse | ReleaseTerminalResponse | WaitForTerminalExitResponse | KillTerminalResponse | CreateElicitationResponse | ConnectMCPResponse | DisconnectMCPResponse | jsontext.Value
}

var clientResponseResultResultAlternatives = altRules{
	reflect.TypeFor[WriteTextFileResponse]():       {{nonNull: true}},
	reflect.TypeFor[ReadTextFileResponse]():        {{nonNull: true, required: []string{"content"}, notNull: []string{"content"}}},
	reflect.TypeFor[RequestPermissionResponse]():   {{nonNull: true, required: []string{"outcome"}, notNull: []string{"outcome"}}},
	reflect.TypeFor[CreateTerminalResponse]():      {{nonNull: true, required: []string{"terminalId"}, notNull: []string{"terminalId"}}},
	reflect.TypeFor[TerminalOutputResponse]():      {{nonNull: true, required: []string{"output", "truncated"}, notNull: []string{"output", "truncated"}}},
	reflect.TypeFor[ReleaseTerminalResponse]():     {{nonNull: true}},
	reflect.TypeFor[WaitForTerminalExitResponse](): {{nonNull: true}},
	reflect.TypeFor[KillTerminalResponse]():        {{nonNull: true}},
	reflect.TypeFor[CreateElicitationResponse]():   {{nonNull: true}},
	reflect.TypeFor[ConnectMCPResponse]():          {{nonNull: true, required: []string{"connectionId"}, notNull: []string{"connectionId"}}},
	reflect.TypeFor[DisconnectMCPResponse]():       {{nonNull: true}},
	reflect.TypeFor[jsontext.Value]():              {{}, {}},
}

// NewClientResponseResultResult encodes value as a ClientResponseResultResult, adding any literal members the alternative
// requires and rejecting values that are not that alternative.
func NewClientResponseResultResult[T ClientResponseResultResultAlternative](value T) (ClientResponseResultResult, error) {
	raw, err := newAlternative("ClientResponseResultResult", clientResponseResultResultAlternatives, value)
	return ClientResponseResultResult{raw: raw}, err
}

// As decodes the payload as the alternative T, or reports why it is not one.
func (v ClientResponseResultResult) As[T ClientResponseResultResultAlternative]() (T, error) {
	return asAlternative[T]("ClientResponseResultResult", clientResponseResultResultAlternatives, v.raw)
}
func (v ClientResponseResultResult) MarshalJSON() ([]byte, error) {
	if len(v.raw) == 0 {
		return []byte("null"), nil
	}
	return v.raw.Clone(), nil
}
func (v *ClientResponseResultResult) UnmarshalJSON(b []byte) error {
	if !jsontext.Value(b).IsValid() {
		return fmt.Errorf("invalid ClientResponseResultResult JSON")
	}
	v.raw = jsontext.Value(b).Clone()
	return nil
}
func (v ClientResponseResultResult) RawJSON() jsontext.Value { return v.raw.Clone() }

// IsZero reports whether no payload is stored, so omitzero omits the field.
func (v ClientResponseResultResult) IsZero() bool { return len(v.raw) == 0 }
func (v ClientResponseResultResult) MarshalJSONTo(enc *jsontext.Encoder) error {
	if len(v.raw) == 0 {
		return enc.WriteValue(jsontext.Value("null"))
	}
	return enc.WriteValue(v.raw)
}
func (v *ClientResponseResultResult) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	raw, err := dec.ReadValue()
	if err != nil {
		return err
	}
	v.raw = raw.Clone()
	return nil
}
func ParseClientResponseResultResult(b []byte) (ClientResponseResultResult, error) {
	var v ClientResponseResultResult
	err := json.Unmarshal(b, &v)
	return v, err
}
