// Code generated by acp-schema from the method table; DO NOT EDIT.

package acp1

import schema "github.com/ironpark/go-acp/schema/v1"

// ProtocolVersion is the ACP protocol version implemented by this package.
const ProtocolVersion = schema.CurrentProtocolVersion

// Every request, response and notification payload, re-exported so that a
// caller implementing [Agent] or [Client] needs one import. Other generated
// types live in the schema package.

type (
	WriteTextFileRequest            = schema.WriteTextFileRequest
	ReadTextFileRequest             = schema.ReadTextFileRequest
	RequestPermissionRequest        = schema.RequestPermissionRequest
	CreateTerminalRequest           = schema.CreateTerminalRequest
	TerminalOutputRequest           = schema.TerminalOutputRequest
	ReleaseTerminalRequest          = schema.ReleaseTerminalRequest
	WaitForTerminalExitRequest      = schema.WaitForTerminalExitRequest
	KillTerminalRequest             = schema.KillTerminalRequest
	CreateElicitationRequest        = schema.CreateElicitationRequest
	ConnectMCPRequest               = schema.ConnectMCPRequest
	MessageMCPRequest               = schema.MessageMCPRequest
	DisconnectMCPRequest            = schema.DisconnectMCPRequest
	ExtRequest                      = schema.ExtRequest
	InitializeResponse              = schema.InitializeResponse
	AuthenticateResponse            = schema.AuthenticateResponse
	ListProvidersResponse           = schema.ListProvidersResponse
	SetProviderResponse             = schema.SetProviderResponse
	DisableProviderResponse         = schema.DisableProviderResponse
	LogoutResponse                  = schema.LogoutResponse
	NewSessionResponse              = schema.NewSessionResponse
	LoadSessionResponse             = schema.LoadSessionResponse
	ListSessionsResponse            = schema.ListSessionsResponse
	DeleteSessionResponse           = schema.DeleteSessionResponse
	ForkSessionResponse             = schema.ForkSessionResponse
	ResumeSessionResponse           = schema.ResumeSessionResponse
	CloseSessionResponse            = schema.CloseSessionResponse
	SetSessionModeResponse          = schema.SetSessionModeResponse
	SetSessionConfigOptionResponse  = schema.SetSessionConfigOptionResponse
	PromptResponse                  = schema.PromptResponse
	StartNesResponse                = schema.StartNesResponse
	SuggestNesResponse              = schema.SuggestNesResponse
	CloseNesResponse                = schema.CloseNesResponse
	ExtResponse                     = schema.ExtResponse
	MessageMCPResponse              = schema.MessageMCPResponse
	SessionNotification             = schema.SessionNotification
	CompleteElicitationNotification = schema.CompleteElicitationNotification
	MessageMCPNotification          = schema.MessageMCPNotification
	ExtNotification                 = schema.ExtNotification
	InitializeRequest               = schema.InitializeRequest
	AuthenticateRequest             = schema.AuthenticateRequest
	ListProvidersRequest            = schema.ListProvidersRequest
	SetProviderRequest              = schema.SetProviderRequest
	DisableProviderRequest          = schema.DisableProviderRequest
	LogoutRequest                   = schema.LogoutRequest
	NewSessionRequest               = schema.NewSessionRequest
	LoadSessionRequest              = schema.LoadSessionRequest
	ListSessionsRequest             = schema.ListSessionsRequest
	DeleteSessionRequest            = schema.DeleteSessionRequest
	ForkSessionRequest              = schema.ForkSessionRequest
	ResumeSessionRequest            = schema.ResumeSessionRequest
	CloseSessionRequest             = schema.CloseSessionRequest
	SetSessionModeRequest           = schema.SetSessionModeRequest
	SetSessionConfigOptionRequest   = schema.SetSessionConfigOptionRequest
	PromptRequest                   = schema.PromptRequest
	StartNesRequest                 = schema.StartNesRequest
	SuggestNesRequest               = schema.SuggestNesRequest
	CloseNesRequest                 = schema.CloseNesRequest
	WriteTextFileResponse           = schema.WriteTextFileResponse
	ReadTextFileResponse            = schema.ReadTextFileResponse
	RequestPermissionResponse       = schema.RequestPermissionResponse
	CreateTerminalResponse          = schema.CreateTerminalResponse
	TerminalOutputResponse          = schema.TerminalOutputResponse
	ReleaseTerminalResponse         = schema.ReleaseTerminalResponse
	WaitForTerminalExitResponse     = schema.WaitForTerminalExitResponse
	KillTerminalResponse            = schema.KillTerminalResponse
	CreateElicitationResponse       = schema.CreateElicitationResponse
	ConnectMCPResponse              = schema.ConnectMCPResponse
	DisconnectMCPResponse           = schema.DisconnectMCPResponse
	CancelNotification              = schema.CancelNotification
	DidOpenDocumentNotification     = schema.DidOpenDocumentNotification
	DidChangeDocumentNotification   = schema.DidChangeDocumentNotification
	DidCloseDocumentNotification    = schema.DidCloseDocumentNotification
	DidSaveDocumentNotification     = schema.DidSaveDocumentNotification
	DidFocusDocumentNotification    = schema.DidFocusDocumentNotification
	AcceptNesNotification           = schema.AcceptNesNotification
	RejectNesNotification           = schema.RejectNesNotification
	CancelRequestNotification       = schema.CancelRequestNotification
)

// Identifiers and values shared across those payloads, with the constants
// and variants that come with them.

type (
	SessionID                            = schema.SessionID
	SessionInfo                          = schema.SessionInfo
	SessionModeID                        = schema.SessionModeID
	SessionConfigOption                  = schema.SessionConfigOption
	SessionConfigOptionVariant           = schema.SessionConfigOptionVariant
	SessionConfigOptionSelect            = schema.SessionConfigOptionSelect
	SessionConfigOptionBoolean           = schema.SessionConfigOptionBoolean
	SessionConfigOptionUnknown           = schema.SessionConfigOptionUnknown
	SessionUpdate                        = schema.SessionUpdate
	SessionUpdateVariant                 = schema.SessionUpdateVariant
	SessionUpdateUserMessageChunk        = schema.SessionUpdateUserMessageChunk
	SessionUpdateAgentMessageChunk       = schema.SessionUpdateAgentMessageChunk
	SessionUpdateAgentThoughtChunk       = schema.SessionUpdateAgentThoughtChunk
	SessionUpdateToolCall                = schema.SessionUpdateToolCall
	SessionUpdateToolCallUpdate          = schema.SessionUpdateToolCallUpdate
	SessionUpdatePlan                    = schema.SessionUpdatePlan
	SessionUpdatePlanUpdate              = schema.SessionUpdatePlanUpdate
	SessionUpdatePlanRemoved             = schema.SessionUpdatePlanRemoved
	SessionUpdateAvailableCommandsUpdate = schema.SessionUpdateAvailableCommandsUpdate
	SessionUpdateCurrentModeUpdate       = schema.SessionUpdateCurrentModeUpdate
	SessionUpdateConfigOptionUpdate      = schema.SessionUpdateConfigOptionUpdate
	SessionUpdateSessionInfoUpdate       = schema.SessionUpdateSessionInfoUpdate
	SessionUpdateUsageUpdate             = schema.SessionUpdateUsageUpdate
	SessionUpdateNotice                  = schema.SessionUpdateNotice
	SessionUpdateCompactionUpdate        = schema.SessionUpdateCompactionUpdate
	SessionUpdateCompactionSummaryChunk  = schema.SessionUpdateCompactionSummaryChunk
	SessionUpdateUnknown                 = schema.SessionUpdateUnknown
	MessageID                            = schema.MessageID
	TerminalID                           = schema.TerminalID
	ToolCallID                           = schema.ToolCallID
	ToolCallContent                      = schema.ToolCallContent
	ToolCallContentVariant               = schema.ToolCallContentVariant
	ToolCallContentContent               = schema.ToolCallContentContent
	ToolCallContentDiff                  = schema.ToolCallContentDiff
	ToolCallContentTerminal              = schema.ToolCallContentTerminal
	ToolCallContentUnknown               = schema.ToolCallContentUnknown
	ToolCallLocation                     = schema.ToolCallLocation
	ToolCallStatus                       = schema.ToolCallStatus
	ToolKind                             = schema.ToolKind
	ContentBlock                         = schema.ContentBlock
	ContentBlockVariant                  = schema.ContentBlockVariant
	ContentBlockText                     = schema.ContentBlockText
	ContentBlockImage                    = schema.ContentBlockImage
	ContentBlockAudio                    = schema.ContentBlockAudio
	ContentBlockResourceLink             = schema.ContentBlockResourceLink
	ContentBlockResource                 = schema.ContentBlockResource
	ContentBlockUnknown                  = schema.ContentBlockUnknown
	PlanEntry                            = schema.PlanEntry
	AvailableCommand                     = schema.AvailableCommand
	Cost                                 = schema.Cost
	StopReason                           = schema.StopReason
	Implementation                       = schema.Implementation
	PermissionOption                     = schema.PermissionOption
	PermissionOptionKind                 = schema.PermissionOptionKind
	ToolCallUpdate                       = schema.ToolCallUpdate
	RequestPermissionOutcome             = schema.RequestPermissionOutcome
	RequestPermissionOutcomeVariant      = schema.RequestPermissionOutcomeVariant
	RequestPermissionOutcomeCancelled    = schema.RequestPermissionOutcomeCancelled
	RequestPermissionOutcomeSelected     = schema.RequestPermissionOutcomeSelected
	RequestPermissionOutcomeUnknown      = schema.RequestPermissionOutcomeUnknown
	PlanEntryStatus                      = schema.PlanEntryStatus
	PlanEntryPriority                    = schema.PlanEntryPriority
	SessionModeState                     = schema.SessionModeState
	SessionMode                          = schema.SessionMode
	TerminalExitStatus                   = schema.TerminalExitStatus
	MCPServer                            = schema.MCPServer
	MCPServerVariant                     = schema.MCPServerVariant
	MCPServerHTTP                        = schema.MCPServerHTTP
	MCPServerSSE                         = schema.MCPServerSSE
	MCPServerACP                         = schema.MCPServerACP
	MCPServerStdio                       = schema.MCPServerStdio
	MCPCapabilities                      = schema.MCPCapabilities
	MCPConnectionID                      = schema.MCPConnectionID
	MCPServerACPID                       = schema.MCPServerACPID
	Meta                                 = schema.Meta
)

const (
	ToolCallStatusPending            = schema.ToolCallStatusPending
	ToolCallStatusInProgress         = schema.ToolCallStatusInProgress
	ToolCallStatusCompleted          = schema.ToolCallStatusCompleted
	ToolCallStatusFailed             = schema.ToolCallStatusFailed
	ToolKindRead                     = schema.ToolKindRead
	ToolKindEdit                     = schema.ToolKindEdit
	ToolKindDelete                   = schema.ToolKindDelete
	ToolKindMove                     = schema.ToolKindMove
	ToolKindSearch                   = schema.ToolKindSearch
	ToolKindExecute                  = schema.ToolKindExecute
	ToolKindThink                    = schema.ToolKindThink
	ToolKindFetch                    = schema.ToolKindFetch
	ToolKindSwitchMode               = schema.ToolKindSwitchMode
	ToolKindOther                    = schema.ToolKindOther
	StopReasonEndTurn                = schema.StopReasonEndTurn
	StopReasonMaxTokens              = schema.StopReasonMaxTokens
	StopReasonMaxTurnRequests        = schema.StopReasonMaxTurnRequests
	StopReasonRefusal                = schema.StopReasonRefusal
	StopReasonCancelled              = schema.StopReasonCancelled
	PermissionOptionKindAllowOnce    = schema.PermissionOptionKindAllowOnce
	PermissionOptionKindAllowAlways  = schema.PermissionOptionKindAllowAlways
	PermissionOptionKindRejectOnce   = schema.PermissionOptionKindRejectOnce
	PermissionOptionKindRejectAlways = schema.PermissionOptionKindRejectAlways
	PlanEntryStatusPending           = schema.PlanEntryStatusPending
	PlanEntryStatusInProgress        = schema.PlanEntryStatusInProgress
	PlanEntryStatusCompleted         = schema.PlanEntryStatusCompleted
	PlanEntryPriorityHigh            = schema.PlanEntryPriorityHigh
	PlanEntryPriorityMedium          = schema.PlanEntryPriorityMedium
	PlanEntryPriorityLow             = schema.PlanEntryPriorityLow
)

// NewSessionConfigOption wraps a variant; a nil variant yields the zero value.
func NewSessionConfigOption(v SessionConfigOptionVariant) SessionConfigOption {
	return schema.NewSessionConfigOption(v)
}

// NewSessionUpdate wraps a variant; a nil variant yields the zero value.
func NewSessionUpdate(v SessionUpdateVariant) SessionUpdate { return schema.NewSessionUpdate(v) }

// NewToolCallContent wraps a variant; a nil variant yields the zero value.
func NewToolCallContent(v ToolCallContentVariant) ToolCallContent {
	return schema.NewToolCallContent(v)
}

// NewContentBlock wraps a variant; a nil variant yields the zero value.
func NewContentBlock(v ContentBlockVariant) ContentBlock { return schema.NewContentBlock(v) }

// NewRequestPermissionOutcome wraps a variant; a nil variant yields the zero value.
func NewRequestPermissionOutcome(v RequestPermissionOutcomeVariant) RequestPermissionOutcome {
	return schema.NewRequestPermissionOutcome(v)
}

// NewMCPServer wraps a variant; a nil variant yields the zero value.
func NewMCPServer(v MCPServerVariant) MCPServer { return schema.NewMCPServer(v) }
