// Code generated by acp-schema from the method table; DO NOT EDIT.

package acpv2

import schema "github.com/ironpark/go-acp/schema/v2"

// ProtocolVersion is the ACP protocol version implemented by this package.
const ProtocolVersion = schema.CurrentProtocolVersion

// Every request, response and notification payload, re-exported so that a
// caller implementing [Agent] or [Client] needs one import. Other generated
// types live in the schema package.

type (
	RequestPermissionRequest        = schema.RequestPermissionRequest
	CreateElicitationRequest        = schema.CreateElicitationRequest
	ConnectMCPRequest               = schema.ConnectMCPRequest
	MessageMCPRequest               = schema.MessageMCPRequest
	DisconnectMCPRequest            = schema.DisconnectMCPRequest
	ExtRequest                      = schema.ExtRequest
	InitializeResponse              = schema.InitializeResponse
	LoginAuthResponse               = schema.LoginAuthResponse
	ListProvidersResponse           = schema.ListProvidersResponse
	SetProviderResponse             = schema.SetProviderResponse
	DisableProviderResponse         = schema.DisableProviderResponse
	LogoutAuthResponse              = schema.LogoutAuthResponse
	NewSessionResponse              = schema.NewSessionResponse
	ListSessionsResponse            = schema.ListSessionsResponse
	DeleteSessionResponse           = schema.DeleteSessionResponse
	ForkSessionResponse             = schema.ForkSessionResponse
	ResumeSessionResponse           = schema.ResumeSessionResponse
	CloseSessionResponse            = schema.CloseSessionResponse
	SetSessionConfigOptionResponse  = schema.SetSessionConfigOptionResponse
	PromptResponse                  = schema.PromptResponse
	StartNesResponse                = schema.StartNesResponse
	SuggestNesResponse              = schema.SuggestNesResponse
	CloseNesResponse                = schema.CloseNesResponse
	ExtResponse                     = schema.ExtResponse
	MessageMCPResponse              = schema.MessageMCPResponse
	UpdateSessionNotification       = schema.UpdateSessionNotification
	CompleteElicitationNotification = schema.CompleteElicitationNotification
	MessageMCPNotification          = schema.MessageMCPNotification
	ExtNotification                 = schema.ExtNotification
	InitializeRequest               = schema.InitializeRequest
	LoginAuthRequest                = schema.LoginAuthRequest
	ListProvidersRequest            = schema.ListProvidersRequest
	SetProviderRequest              = schema.SetProviderRequest
	DisableProviderRequest          = schema.DisableProviderRequest
	LogoutAuthRequest               = schema.LogoutAuthRequest
	NewSessionRequest               = schema.NewSessionRequest
	ListSessionsRequest             = schema.ListSessionsRequest
	DeleteSessionRequest            = schema.DeleteSessionRequest
	ForkSessionRequest              = schema.ForkSessionRequest
	ResumeSessionRequest            = schema.ResumeSessionRequest
	CloseSessionRequest             = schema.CloseSessionRequest
	SetSessionConfigOptionRequest   = schema.SetSessionConfigOptionRequest
	PromptRequest                   = schema.PromptRequest
	StartNesRequest                 = schema.StartNesRequest
	SuggestNesRequest               = schema.SuggestNesRequest
	CloseNesRequest                 = schema.CloseNesRequest
	RequestPermissionResponse       = schema.RequestPermissionResponse
	CreateElicitationResponse       = schema.CreateElicitationResponse
	ConnectMCPResponse              = schema.ConnectMCPResponse
	DisconnectMCPResponse           = schema.DisconnectMCPResponse
	CancelSessionNotification       = schema.CancelSessionNotification
	DidOpenDocumentNotification     = schema.DidOpenDocumentNotification
	DidChangeDocumentNotification   = schema.DidChangeDocumentNotification
	DidCloseDocumentNotification    = schema.DidCloseDocumentNotification
	DidSaveDocumentNotification     = schema.DidSaveDocumentNotification
	DidFocusDocumentNotification    = schema.DidFocusDocumentNotification
	AcceptNesNotification           = schema.AcceptNesNotification
	RejectNesNotification           = schema.RejectNesNotification
	CancelRequestNotification       = schema.CancelRequestNotification
)

// Identifiers and values shared across those payloads.

type (
	SessionID           = schema.SessionID
	SessionInfo         = schema.SessionInfo
	SessionConfigOption = schema.SessionConfigOption
	SessionUpdate       = schema.SessionUpdate
	MessageID           = schema.MessageID
	ToolCallID          = schema.ToolCallID
	ContentBlock        = schema.ContentBlock
	AbsolutePath        = schema.AbsolutePath
	MCPConnectionID     = schema.MCPConnectionID
	MCPServerACPID      = schema.MCPServerACPID
	StopReason          = schema.StopReason
	Meta                = schema.Meta
)
